/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// SheetsAPIService SheetsAPI service
type SheetsAPIService service

type ApiCreateSheetRequest struct {
	ctx           context.Context
	ApiService    *SheetsAPIService
	authorization *string
	itemType      string
	itemId        int32
	sheetData     *SheetData
}

func (r ApiCreateSheetRequest) Authorization(authorization string) ApiCreateSheetRequest {
	r.authorization = &authorization
	return r
}

// Sheet object that needs to be added to the object
func (r ApiCreateSheetRequest) SheetData(sheetData SheetData) ApiCreateSheetRequest {
	r.sheetData = &sheetData
	return r
}

func (r ApiCreateSheetRequest) Execute() (*http.Response, error) {
	return r.ApiService.CreateSheetExecute(r)
}

/*
CreateSheet Adds a new sheet to the object

New Sheet will be added to the object

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param itemType Object ItemType
	@param itemId Object ItemID
	@return ApiCreateSheetRequest
*/
func (a *SheetsAPIService) CreateSheet(ctx context.Context, itemType string, itemId int32) ApiCreateSheetRequest {
	return ApiCreateSheetRequest{
		ApiService: a,
		ctx:        ctx,
		itemType:   itemType,
		itemId:     itemId,
	}
}

// Execute executes the request
func (a *SheetsAPIService) CreateSheetExecute(r ApiCreateSheetRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPost
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SheetsAPIService.CreateSheet")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/2.0/sheets/{itemType}/{itemId}"
	localVarPath = strings.Replace(localVarPath, "{"+"itemType"+"}", url.PathEscape(parameterValueToString(r.itemType, "itemType")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"itemId"+"}", url.PathEscape(parameterValueToString(r.itemId, "itemId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.authorization == nil {
		return nil, reportError("authorization is required and must be specified")
	}
	if r.sheetData == nil {
		return nil, reportError("sheetData is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "authorization", r.authorization, "simple", "")
	// body params
	localVarPostBody = r.sheetData
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v RequestError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiDeleteSheetByIdRequest struct {
	ctx           context.Context
	ApiService    *SheetsAPIService
	authorization *string
	sheetId       int32
}

func (r ApiDeleteSheetByIdRequest) Authorization(authorization string) ApiDeleteSheetByIdRequest {
	r.authorization = &authorization
	return r
}

func (r ApiDeleteSheetByIdRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteSheetByIdExecute(r)
}

/*
DeleteSheetById Deletes a sheet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param sheetId A Single SheetId
	@return ApiDeleteSheetByIdRequest
*/
func (a *SheetsAPIService) DeleteSheetById(ctx context.Context, sheetId int32) ApiDeleteSheetByIdRequest {
	return ApiDeleteSheetByIdRequest{
		ApiService: a,
		ctx:        ctx,
		sheetId:    sheetId,
	}
}

// Execute executes the request
func (a *SheetsAPIService) DeleteSheetByIdExecute(r ApiDeleteSheetByIdRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SheetsAPIService.DeleteSheetById")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/2.0/sheets/{sheetId}/"
	localVarPath = strings.Replace(localVarPath, "{"+"sheetId"+"}", url.PathEscape(parameterValueToString(r.sheetId, "sheetId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.authorization == nil {
		return nil, reportError("authorization is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "authorization", r.authorization, "simple", "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v RequestError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarHTTPResponse, newErr
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetObjectSheetByIdRequest struct {
	ctx           context.Context
	ApiService    *SheetsAPIService
	authorization *string
	sheetId       int32
}

func (r ApiGetObjectSheetByIdRequest) Authorization(authorization string) ApiGetObjectSheetByIdRequest {
	r.authorization = &authorization
	return r
}

func (r ApiGetObjectSheetByIdRequest) Execute() (*SheetData, *http.Response, error) {
	return r.ApiService.GetObjectSheetByIdExecute(r)
}

/*
GetObjectSheetById Fetch object sheet

Fetch object sheet.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param sheetId A Single SheetId
	@return ApiGetObjectSheetByIdRequest
*/
func (a *SheetsAPIService) GetObjectSheetById(ctx context.Context, sheetId int32) ApiGetObjectSheetByIdRequest {
	return ApiGetObjectSheetByIdRequest{
		ApiService: a,
		ctx:        ctx,
		sheetId:    sheetId,
	}
}

// Execute executes the request
//
//	@return SheetData
func (a *SheetsAPIService) GetObjectSheetByIdExecute(r ApiGetObjectSheetByIdRequest) (*SheetData, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *SheetData
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SheetsAPIService.GetObjectSheetById")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/2.0/sheets/{sheetId}/"
	localVarPath = strings.Replace(localVarPath, "{"+"sheetId"+"}", url.PathEscape(parameterValueToString(r.sheetId, "sheetId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.authorization == nil {
		return localVarReturnValue, nil, reportError("authorization is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "authorization", r.authorization, "simple", "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v RequestError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateSheetByIdRequest struct {
	ctx           context.Context
	ApiService    *SheetsAPIService
	authorization *string
	sheetId       int32
	sheetData     *SheetData
}

func (r ApiUpdateSheetByIdRequest) Authorization(authorization string) ApiUpdateSheetByIdRequest {
	r.authorization = &authorization
	return r
}

// Sheet fields that needs to be updated to the portal
func (r ApiUpdateSheetByIdRequest) SheetData(sheetData SheetData) ApiUpdateSheetByIdRequest {
	r.sheetData = &sheetData
	return r
}

func (r ApiUpdateSheetByIdRequest) Execute() (*http.Response, error) {
	return r.ApiService.UpdateSheetByIdExecute(r)
}

/*
UpdateSheetById Updates a single Sheet id

Updates specific fields on an entity (RFC 7396)

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param sheetId A Single SheetId
	@return ApiUpdateSheetByIdRequest
*/
func (a *SheetsAPIService) UpdateSheetById(ctx context.Context, sheetId int32) ApiUpdateSheetByIdRequest {
	return ApiUpdateSheetByIdRequest{
		ApiService: a,
		ctx:        ctx,
		sheetId:    sheetId,
	}
}

// Execute executes the request
func (a *SheetsAPIService) UpdateSheetByIdExecute(r ApiUpdateSheetByIdRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPatch
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SheetsAPIService.UpdateSheetById")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/2.0/sheets/{sheetId}/"
	localVarPath = strings.Replace(localVarPath, "{"+"sheetId"+"}", url.PathEscape(parameterValueToString(r.sheetId, "sheetId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.authorization == nil {
		return nil, reportError("authorization is required and must be specified")
	}
	if r.sheetData == nil {
		return nil, reportError("sheetData is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/merge-patch+json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "authorization", r.authorization, "simple", "")
	// body params
	localVarPostBody = r.sheetData
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v RequestError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarHTTPResponse, newErr
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
