/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the MainContactDataContainer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MainContactDataContainer{}

// MainContactDataContainer struct for MainContactDataContainer
type MainContactDataContainer struct {
	// The requested offset (number of skipped results) of the call.
	Offset *int32 `json:"offset,omitempty"`
	// The requested result limit.
	Limit *int32 `json:"limit,omitempty"`
	// The total number of resources available given the current filter set.
	Total *int64 `json:"total,omitempty"`
	// The total number of results returned by this call.
	Count *int64 `json:"count,omitempty"`
	// The list of Portal companies main contacts returned by the call.
	Results              []MainContact `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MainContactDataContainer MainContactDataContainer

// NewMainContactDataContainer instantiates a new MainContactDataContainer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMainContactDataContainer() *MainContactDataContainer {
	this := MainContactDataContainer{}
	return &this
}

// NewMainContactDataContainerWithDefaults instantiates a new MainContactDataContainer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMainContactDataContainerWithDefaults() *MainContactDataContainer {
	this := MainContactDataContainer{}
	return &this
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *MainContactDataContainer) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainContactDataContainer) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *MainContactDataContainer) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *MainContactDataContainer) SetOffset(v int32) {
	o.Offset = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *MainContactDataContainer) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainContactDataContainer) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *MainContactDataContainer) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *MainContactDataContainer) SetLimit(v int32) {
	o.Limit = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *MainContactDataContainer) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainContactDataContainer) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *MainContactDataContainer) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *MainContactDataContainer) SetTotal(v int64) {
	o.Total = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *MainContactDataContainer) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainContactDataContainer) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *MainContactDataContainer) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *MainContactDataContainer) SetCount(v int64) {
	o.Count = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *MainContactDataContainer) GetResults() []MainContact {
	if o == nil || IsNil(o.Results) {
		var ret []MainContact
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainContactDataContainer) GetResultsOk() ([]MainContact, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *MainContactDataContainer) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []MainContact and assigns it to the Results field.
func (o *MainContactDataContainer) SetResults(v []MainContact) {
	o.Results = v
}

func (o MainContactDataContainer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MainContactDataContainer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MainContactDataContainer) UnmarshalJSON(data []byte) (err error) {
	varMainContactDataContainer := _MainContactDataContainer{}

	err = json.Unmarshal(data, &varMainContactDataContainer)

	if err != nil {
		return err
	}

	*o = MainContactDataContainer(varMainContactDataContainer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "offset")
		delete(additionalProperties, "limit")
		delete(additionalProperties, "total")
		delete(additionalProperties, "count")
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMainContactDataContainer struct {
	value *MainContactDataContainer
	isSet bool
}

func (v NullableMainContactDataContainer) Get() *MainContactDataContainer {
	return v.value
}

func (v *NullableMainContactDataContainer) Set(val *MainContactDataContainer) {
	v.value = val
	v.isSet = true
}

func (v NullableMainContactDataContainer) IsSet() bool {
	return v.isSet
}

func (v *NullableMainContactDataContainer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMainContactDataContainer(val *MainContactDataContainer) *NullableMainContactDataContainer {
	return &NullableMainContactDataContainer{value: val, isSet: true}
}

func (v NullableMainContactDataContainer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMainContactDataContainer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
