/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Company type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Company{}

// Company struct for Company
type Company struct {
	// The unique ID of the company.
	Id            *int64            `json:"id,omitempty"`
	ParentCompany *CompanyReference `json:"parentCompany,omitempty"`
	// The name of the company.
	Name             string           `json:"name"`
	Type             CompanyType      `json:"type"`
	Contact          ContactReference `json:"contact"`
	AssignedEngineer User             `json:"assignedEngineer"`
	AccountManager   User             `json:"accountManager"`
	// The JSON array designating the Main Contacts.
	MainContacts []MainContact  `json:"mainContacts,omitempty"`
	Site         *SiteReference `json:"site,omitempty"`
	Address      *Address       `json:"address,omitempty"`
	// The date your company engaged this company.
	StartDate *string `json:"startDate,omitempty"`
	// A slogan or description of the company.
	Description *string `json:"description,omitempty"`
	// Abbreviation - Company Code/ID
	Abbreviation *string `json:"abbreviation,omitempty"`
	// The website of the company.
	WebSite *string `json:"webSite,omitempty"`
	// The status of the company.
	Status *string `json:"status,omitempty"`
	// The notes of the company.
	Notes *string `json:"notes,omitempty"`
	// Allow HTML or not.
	NotesHtml *bool `json:"notesHtml,omitempty"`
	// The remote access notes of the company.
	RemoteAccessNotes *string `json:"remoteAccessNotes,omitempty"`
	// Allow HTML or not.
	RemoteAccessNotesHtml *bool `json:"remoteAccessNotesHtml,omitempty"`
	// The foreign id of the synced integration.
	ForeignId *int64 `json:"foreignId,omitempty"`
	// The foreign type of the synced integration.
	ForeignType *string `json:"foreignType,omitempty"`
	// The link of the company.
	Url *string `json:"url,omitempty"`
	// The date the company was most recently modified.
	Modified             *time.Time `json:"modified,omitempty"`
	Sheets               *Sheet     `json:"sheets,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Company Company

// NewCompany instantiates a new Company object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompany(name string, type_ CompanyType, contact ContactReference, assignedEngineer User, accountManager User) *Company {
	this := Company{}
	this.Name = name
	this.Type = type_
	this.Contact = contact
	this.AssignedEngineer = assignedEngineer
	this.AccountManager = accountManager
	return &this
}

// NewCompanyWithDefaults instantiates a new Company object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyWithDefaults() *Company {
	this := Company{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Company) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Company) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *Company) SetId(v int64) {
	o.Id = &v
}

// GetParentCompany returns the ParentCompany field value if set, zero value otherwise.
func (o *Company) GetParentCompany() CompanyReference {
	if o == nil || IsNil(o.ParentCompany) {
		var ret CompanyReference
		return ret
	}
	return *o.ParentCompany
}

// GetParentCompanyOk returns a tuple with the ParentCompany field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetParentCompanyOk() (*CompanyReference, bool) {
	if o == nil || IsNil(o.ParentCompany) {
		return nil, false
	}
	return o.ParentCompany, true
}

// HasParentCompany returns a boolean if a field has been set.
func (o *Company) HasParentCompany() bool {
	if o != nil && !IsNil(o.ParentCompany) {
		return true
	}

	return false
}

// SetParentCompany gets a reference to the given CompanyReference and assigns it to the ParentCompany field.
func (o *Company) SetParentCompany(v CompanyReference) {
	o.ParentCompany = &v
}

// GetName returns the Name field value
func (o *Company) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Company) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Company) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *Company) GetType() CompanyType {
	if o == nil {
		var ret CompanyType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Company) GetTypeOk() (*CompanyType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Company) SetType(v CompanyType) {
	o.Type = v
}

// GetContact returns the Contact field value
func (o *Company) GetContact() ContactReference {
	if o == nil {
		var ret ContactReference
		return ret
	}

	return o.Contact
}

// GetContactOk returns a tuple with the Contact field value
// and a boolean to check if the value has been set.
func (o *Company) GetContactOk() (*ContactReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Contact, true
}

// SetContact sets field value
func (o *Company) SetContact(v ContactReference) {
	o.Contact = v
}

// GetAssignedEngineer returns the AssignedEngineer field value
func (o *Company) GetAssignedEngineer() User {
	if o == nil {
		var ret User
		return ret
	}

	return o.AssignedEngineer
}

// GetAssignedEngineerOk returns a tuple with the AssignedEngineer field value
// and a boolean to check if the value has been set.
func (o *Company) GetAssignedEngineerOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssignedEngineer, true
}

// SetAssignedEngineer sets field value
func (o *Company) SetAssignedEngineer(v User) {
	o.AssignedEngineer = v
}

// GetAccountManager returns the AccountManager field value
func (o *Company) GetAccountManager() User {
	if o == nil {
		var ret User
		return ret
	}

	return o.AccountManager
}

// GetAccountManagerOk returns a tuple with the AccountManager field value
// and a boolean to check if the value has been set.
func (o *Company) GetAccountManagerOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountManager, true
}

// SetAccountManager sets field value
func (o *Company) SetAccountManager(v User) {
	o.AccountManager = v
}

// GetMainContacts returns the MainContacts field value if set, zero value otherwise.
func (o *Company) GetMainContacts() []MainContact {
	if o == nil || IsNil(o.MainContacts) {
		var ret []MainContact
		return ret
	}
	return o.MainContacts
}

// GetMainContactsOk returns a tuple with the MainContacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetMainContactsOk() ([]MainContact, bool) {
	if o == nil || IsNil(o.MainContacts) {
		return nil, false
	}
	return o.MainContacts, true
}

// HasMainContacts returns a boolean if a field has been set.
func (o *Company) HasMainContacts() bool {
	if o != nil && !IsNil(o.MainContacts) {
		return true
	}

	return false
}

// SetMainContacts gets a reference to the given []MainContact and assigns it to the MainContacts field.
func (o *Company) SetMainContacts(v []MainContact) {
	o.MainContacts = v
}

// GetSite returns the Site field value if set, zero value otherwise.
func (o *Company) GetSite() SiteReference {
	if o == nil || IsNil(o.Site) {
		var ret SiteReference
		return ret
	}
	return *o.Site
}

// GetSiteOk returns a tuple with the Site field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetSiteOk() (*SiteReference, bool) {
	if o == nil || IsNil(o.Site) {
		return nil, false
	}
	return o.Site, true
}

// HasSite returns a boolean if a field has been set.
func (o *Company) HasSite() bool {
	if o != nil && !IsNil(o.Site) {
		return true
	}

	return false
}

// SetSite gets a reference to the given SiteReference and assigns it to the Site field.
func (o *Company) SetSite(v SiteReference) {
	o.Site = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *Company) GetAddress() Address {
	if o == nil || IsNil(o.Address) {
		var ret Address
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetAddressOk() (*Address, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *Company) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given Address and assigns it to the Address field.
func (o *Company) SetAddress(v Address) {
	o.Address = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *Company) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *Company) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *Company) SetStartDate(v string) {
	o.StartDate = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Company) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Company) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Company) SetDescription(v string) {
	o.Description = &v
}

// GetAbbreviation returns the Abbreviation field value if set, zero value otherwise.
func (o *Company) GetAbbreviation() string {
	if o == nil || IsNil(o.Abbreviation) {
		var ret string
		return ret
	}
	return *o.Abbreviation
}

// GetAbbreviationOk returns a tuple with the Abbreviation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetAbbreviationOk() (*string, bool) {
	if o == nil || IsNil(o.Abbreviation) {
		return nil, false
	}
	return o.Abbreviation, true
}

// HasAbbreviation returns a boolean if a field has been set.
func (o *Company) HasAbbreviation() bool {
	if o != nil && !IsNil(o.Abbreviation) {
		return true
	}

	return false
}

// SetAbbreviation gets a reference to the given string and assigns it to the Abbreviation field.
func (o *Company) SetAbbreviation(v string) {
	o.Abbreviation = &v
}

// GetWebSite returns the WebSite field value if set, zero value otherwise.
func (o *Company) GetWebSite() string {
	if o == nil || IsNil(o.WebSite) {
		var ret string
		return ret
	}
	return *o.WebSite
}

// GetWebSiteOk returns a tuple with the WebSite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetWebSiteOk() (*string, bool) {
	if o == nil || IsNil(o.WebSite) {
		return nil, false
	}
	return o.WebSite, true
}

// HasWebSite returns a boolean if a field has been set.
func (o *Company) HasWebSite() bool {
	if o != nil && !IsNil(o.WebSite) {
		return true
	}

	return false
}

// SetWebSite gets a reference to the given string and assigns it to the WebSite field.
func (o *Company) SetWebSite(v string) {
	o.WebSite = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Company) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Company) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Company) SetStatus(v string) {
	o.Status = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *Company) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *Company) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *Company) SetNotes(v string) {
	o.Notes = &v
}

// GetNotesHtml returns the NotesHtml field value if set, zero value otherwise.
func (o *Company) GetNotesHtml() bool {
	if o == nil || IsNil(o.NotesHtml) {
		var ret bool
		return ret
	}
	return *o.NotesHtml
}

// GetNotesHtmlOk returns a tuple with the NotesHtml field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetNotesHtmlOk() (*bool, bool) {
	if o == nil || IsNil(o.NotesHtml) {
		return nil, false
	}
	return o.NotesHtml, true
}

// HasNotesHtml returns a boolean if a field has been set.
func (o *Company) HasNotesHtml() bool {
	if o != nil && !IsNil(o.NotesHtml) {
		return true
	}

	return false
}

// SetNotesHtml gets a reference to the given bool and assigns it to the NotesHtml field.
func (o *Company) SetNotesHtml(v bool) {
	o.NotesHtml = &v
}

// GetRemoteAccessNotes returns the RemoteAccessNotes field value if set, zero value otherwise.
func (o *Company) GetRemoteAccessNotes() string {
	if o == nil || IsNil(o.RemoteAccessNotes) {
		var ret string
		return ret
	}
	return *o.RemoteAccessNotes
}

// GetRemoteAccessNotesOk returns a tuple with the RemoteAccessNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetRemoteAccessNotesOk() (*string, bool) {
	if o == nil || IsNil(o.RemoteAccessNotes) {
		return nil, false
	}
	return o.RemoteAccessNotes, true
}

// HasRemoteAccessNotes returns a boolean if a field has been set.
func (o *Company) HasRemoteAccessNotes() bool {
	if o != nil && !IsNil(o.RemoteAccessNotes) {
		return true
	}

	return false
}

// SetRemoteAccessNotes gets a reference to the given string and assigns it to the RemoteAccessNotes field.
func (o *Company) SetRemoteAccessNotes(v string) {
	o.RemoteAccessNotes = &v
}

// GetRemoteAccessNotesHtml returns the RemoteAccessNotesHtml field value if set, zero value otherwise.
func (o *Company) GetRemoteAccessNotesHtml() bool {
	if o == nil || IsNil(o.RemoteAccessNotesHtml) {
		var ret bool
		return ret
	}
	return *o.RemoteAccessNotesHtml
}

// GetRemoteAccessNotesHtmlOk returns a tuple with the RemoteAccessNotesHtml field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetRemoteAccessNotesHtmlOk() (*bool, bool) {
	if o == nil || IsNil(o.RemoteAccessNotesHtml) {
		return nil, false
	}
	return o.RemoteAccessNotesHtml, true
}

// HasRemoteAccessNotesHtml returns a boolean if a field has been set.
func (o *Company) HasRemoteAccessNotesHtml() bool {
	if o != nil && !IsNil(o.RemoteAccessNotesHtml) {
		return true
	}

	return false
}

// SetRemoteAccessNotesHtml gets a reference to the given bool and assigns it to the RemoteAccessNotesHtml field.
func (o *Company) SetRemoteAccessNotesHtml(v bool) {
	o.RemoteAccessNotesHtml = &v
}

// GetForeignId returns the ForeignId field value if set, zero value otherwise.
func (o *Company) GetForeignId() int64 {
	if o == nil || IsNil(o.ForeignId) {
		var ret int64
		return ret
	}
	return *o.ForeignId
}

// GetForeignIdOk returns a tuple with the ForeignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetForeignIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ForeignId) {
		return nil, false
	}
	return o.ForeignId, true
}

// HasForeignId returns a boolean if a field has been set.
func (o *Company) HasForeignId() bool {
	if o != nil && !IsNil(o.ForeignId) {
		return true
	}

	return false
}

// SetForeignId gets a reference to the given int64 and assigns it to the ForeignId field.
func (o *Company) SetForeignId(v int64) {
	o.ForeignId = &v
}

// GetForeignType returns the ForeignType field value if set, zero value otherwise.
func (o *Company) GetForeignType() string {
	if o == nil || IsNil(o.ForeignType) {
		var ret string
		return ret
	}
	return *o.ForeignType
}

// GetForeignTypeOk returns a tuple with the ForeignType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetForeignTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ForeignType) {
		return nil, false
	}
	return o.ForeignType, true
}

// HasForeignType returns a boolean if a field has been set.
func (o *Company) HasForeignType() bool {
	if o != nil && !IsNil(o.ForeignType) {
		return true
	}

	return false
}

// SetForeignType gets a reference to the given string and assigns it to the ForeignType field.
func (o *Company) SetForeignType(v string) {
	o.ForeignType = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Company) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Company) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Company) SetUrl(v string) {
	o.Url = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *Company) GetModified() time.Time {
	if o == nil || IsNil(o.Modified) {
		var ret time.Time
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *Company) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given time.Time and assigns it to the Modified field.
func (o *Company) SetModified(v time.Time) {
	o.Modified = &v
}

// GetSheets returns the Sheets field value if set, zero value otherwise.
func (o *Company) GetSheets() Sheet {
	if o == nil || IsNil(o.Sheets) {
		var ret Sheet
		return ret
	}
	return *o.Sheets
}

// GetSheetsOk returns a tuple with the Sheets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetSheetsOk() (*Sheet, bool) {
	if o == nil || IsNil(o.Sheets) {
		return nil, false
	}
	return o.Sheets, true
}

// HasSheets returns a boolean if a field has been set.
func (o *Company) HasSheets() bool {
	if o != nil && !IsNil(o.Sheets) {
		return true
	}

	return false
}

// SetSheets gets a reference to the given Sheet and assigns it to the Sheets field.
func (o *Company) SetSheets(v Sheet) {
	o.Sheets = &v
}

func (o Company) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Company) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ParentCompany) {
		toSerialize["parentCompany"] = o.ParentCompany
	}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["contact"] = o.Contact
	toSerialize["assignedEngineer"] = o.AssignedEngineer
	toSerialize["accountManager"] = o.AccountManager
	if !IsNil(o.MainContacts) {
		toSerialize["mainContacts"] = o.MainContacts
	}
	if !IsNil(o.Site) {
		toSerialize["site"] = o.Site
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Abbreviation) {
		toSerialize["abbreviation"] = o.Abbreviation
	}
	if !IsNil(o.WebSite) {
		toSerialize["webSite"] = o.WebSite
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.NotesHtml) {
		toSerialize["notesHtml"] = o.NotesHtml
	}
	if !IsNil(o.RemoteAccessNotes) {
		toSerialize["remoteAccessNotes"] = o.RemoteAccessNotes
	}
	if !IsNil(o.RemoteAccessNotesHtml) {
		toSerialize["remoteAccessNotesHtml"] = o.RemoteAccessNotesHtml
	}
	if !IsNil(o.ForeignId) {
		toSerialize["foreignId"] = o.ForeignId
	}
	if !IsNil(o.ForeignType) {
		toSerialize["foreignType"] = o.ForeignType
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	if !IsNil(o.Sheets) {
		toSerialize["sheets"] = o.Sheets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Company) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
		"contact",
		"assignedEngineer",
		"accountManager",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompany := _Company{}

	err = json.Unmarshal(data, &varCompany)

	if err != nil {
		return err
	}

	*o = Company(varCompany)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "parentCompany")
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		delete(additionalProperties, "contact")
		delete(additionalProperties, "assignedEngineer")
		delete(additionalProperties, "accountManager")
		delete(additionalProperties, "mainContacts")
		delete(additionalProperties, "site")
		delete(additionalProperties, "address")
		delete(additionalProperties, "startDate")
		delete(additionalProperties, "description")
		delete(additionalProperties, "abbreviation")
		delete(additionalProperties, "webSite")
		delete(additionalProperties, "status")
		delete(additionalProperties, "notes")
		delete(additionalProperties, "notesHtml")
		delete(additionalProperties, "remoteAccessNotes")
		delete(additionalProperties, "remoteAccessNotesHtml")
		delete(additionalProperties, "foreignId")
		delete(additionalProperties, "foreignType")
		delete(additionalProperties, "url")
		delete(additionalProperties, "modified")
		delete(additionalProperties, "sheets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCompany struct {
	value *Company
	isSet bool
}

func (v NullableCompany) Get() *Company {
	return v.value
}

func (v *NullableCompany) Set(val *Company) {
	v.value = val
	v.isSet = true
}

func (v NullableCompany) IsSet() bool {
	return v.isSet
}

func (v *NullableCompany) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompany(val *Company) *NullableCompany {
	return &NullableCompany{value: val, isSet: true}
}

func (v NullableCompany) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompany) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
