/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the SwitchPortReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SwitchPortReference{}

// SwitchPortReference struct for SwitchPortReference
type SwitchPortReference struct {
	// The unique ID of the Switch Port.
	Id                   *int64 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SwitchPortReference SwitchPortReference

// NewSwitchPortReference instantiates a new SwitchPortReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSwitchPortReference() *SwitchPortReference {
	this := SwitchPortReference{}
	return &this
}

// NewSwitchPortReferenceWithDefaults instantiates a new SwitchPortReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSwitchPortReferenceWithDefaults() *SwitchPortReference {
	this := SwitchPortReference{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SwitchPortReference) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwitchPortReference) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SwitchPortReference) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *SwitchPortReference) SetId(v int64) {
	o.Id = &v
}

func (o SwitchPortReference) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SwitchPortReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SwitchPortReference) UnmarshalJSON(data []byte) (err error) {
	varSwitchPortReference := _SwitchPortReference{}

	err = json.Unmarshal(data, &varSwitchPortReference)

	if err != nil {
		return err
	}

	*o = SwitchPortReference(varSwitchPortReference)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSwitchPortReference struct {
	value *SwitchPortReference
	isSet bool
}

func (v NullableSwitchPortReference) Get() *SwitchPortReference {
	return v.value
}

func (v *NullableSwitchPortReference) Set(val *SwitchPortReference) {
	v.value = val
	v.isSet = true
}

func (v NullableSwitchPortReference) IsSet() bool {
	return v.isSet
}

func (v *NullableSwitchPortReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSwitchPortReference(val *SwitchPortReference) *NullableSwitchPortReference {
	return &NullableSwitchPortReference{value: val, isSet: true}
}

func (v NullableSwitchPortReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSwitchPortReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
