/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the DeviceReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceReference{}

// DeviceReference struct for DeviceReference
type DeviceReference struct {
	// The unique ID of the device.
	Id *int64 `json:"id,omitempty"`
	// Friendly Device Name
	Name *string `json:"name,omitempty"`
	// Hostname
	HostName             *string `json:"hostName,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeviceReference DeviceReference

// NewDeviceReference instantiates a new DeviceReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceReference() *DeviceReference {
	this := DeviceReference{}
	return &this
}

// NewDeviceReferenceWithDefaults instantiates a new DeviceReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceReferenceWithDefaults() *DeviceReference {
	this := DeviceReference{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeviceReference) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceReference) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeviceReference) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *DeviceReference) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DeviceReference) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceReference) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DeviceReference) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DeviceReference) SetName(v string) {
	o.Name = &v
}

// GetHostName returns the HostName field value if set, zero value otherwise.
func (o *DeviceReference) GetHostName() string {
	if o == nil || IsNil(o.HostName) {
		var ret string
		return ret
	}
	return *o.HostName
}

// GetHostNameOk returns a tuple with the HostName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceReference) GetHostNameOk() (*string, bool) {
	if o == nil || IsNil(o.HostName) {
		return nil, false
	}
	return o.HostName, true
}

// HasHostName returns a boolean if a field has been set.
func (o *DeviceReference) HasHostName() bool {
	if o != nil && !IsNil(o.HostName) {
		return true
	}

	return false
}

// SetHostName gets a reference to the given string and assigns it to the HostName field.
func (o *DeviceReference) SetHostName(v string) {
	o.HostName = &v
}

func (o DeviceReference) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.HostName) {
		toSerialize["hostName"] = o.HostName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeviceReference) UnmarshalJSON(data []byte) (err error) {
	varDeviceReference := _DeviceReference{}

	err = json.Unmarshal(data, &varDeviceReference)

	if err != nil {
		return err
	}

	*o = DeviceReference(varDeviceReference)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "hostName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeviceReference struct {
	value *DeviceReference
	isSet bool
}

func (v NullableDeviceReference) Get() *DeviceReference {
	return v.value
}

func (v *NullableDeviceReference) Set(val *DeviceReference) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceReference) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceReference(val *DeviceReference) *NullableDeviceReference {
	return &NullableDeviceReference{value: val, isSet: true}
}

func (v NullableDeviceReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
