/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the AccountTypeDataContainer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountTypeDataContainer{}

// AccountTypeDataContainer struct for AccountTypeDataContainer
type AccountTypeDataContainer struct {
	// The requested offset (number of skipped results) of the call.
	Offset *int32 `json:"offset,omitempty"`
	// The requested result limit.
	Limit *int32 `json:"limit,omitempty"`
	// The total number of resources available given the current filter set.
	Total *int64 `json:"total,omitempty"`
	// The total number of results returned by this call.
	Count *int64 `json:"count,omitempty"`
	// The list of account types returned by the call.
	Results              []AccountType `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AccountTypeDataContainer AccountTypeDataContainer

// NewAccountTypeDataContainer instantiates a new AccountTypeDataContainer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountTypeDataContainer() *AccountTypeDataContainer {
	this := AccountTypeDataContainer{}
	return &this
}

// NewAccountTypeDataContainerWithDefaults instantiates a new AccountTypeDataContainer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountTypeDataContainerWithDefaults() *AccountTypeDataContainer {
	this := AccountTypeDataContainer{}
	return &this
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *AccountTypeDataContainer) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTypeDataContainer) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *AccountTypeDataContainer) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *AccountTypeDataContainer) SetOffset(v int32) {
	o.Offset = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *AccountTypeDataContainer) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTypeDataContainer) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *AccountTypeDataContainer) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *AccountTypeDataContainer) SetLimit(v int32) {
	o.Limit = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *AccountTypeDataContainer) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTypeDataContainer) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *AccountTypeDataContainer) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *AccountTypeDataContainer) SetTotal(v int64) {
	o.Total = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *AccountTypeDataContainer) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTypeDataContainer) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *AccountTypeDataContainer) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *AccountTypeDataContainer) SetCount(v int64) {
	o.Count = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *AccountTypeDataContainer) GetResults() []AccountType {
	if o == nil || IsNil(o.Results) {
		var ret []AccountType
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTypeDataContainer) GetResultsOk() ([]AccountType, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *AccountTypeDataContainer) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []AccountType and assigns it to the Results field.
func (o *AccountTypeDataContainer) SetResults(v []AccountType) {
	o.Results = v
}

func (o AccountTypeDataContainer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountTypeDataContainer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccountTypeDataContainer) UnmarshalJSON(data []byte) (err error) {
	varAccountTypeDataContainer := _AccountTypeDataContainer{}

	err = json.Unmarshal(data, &varAccountTypeDataContainer)

	if err != nil {
		return err
	}

	*o = AccountTypeDataContainer(varAccountTypeDataContainer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "offset")
		delete(additionalProperties, "limit")
		delete(additionalProperties, "total")
		delete(additionalProperties, "count")
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccountTypeDataContainer struct {
	value *AccountTypeDataContainer
	isSet bool
}

func (v NullableAccountTypeDataContainer) Get() *AccountTypeDataContainer {
	return v.value
}

func (v *NullableAccountTypeDataContainer) Set(val *AccountTypeDataContainer) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountTypeDataContainer) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountTypeDataContainer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountTypeDataContainer(val *AccountTypeDataContainer) *NullableAccountTypeDataContainer {
	return &NullableAccountTypeDataContainer{value: val, isSet: true}
}

func (v NullableAccountTypeDataContainer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountTypeDataContainer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
