/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the IPReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPReference{}

// IPReference struct for IPReference
type IPReference struct {
	// The unique ID of the ip address.
	Id *int64 `json:"id,omitempty"`
	// The ip address.
	Ip                   *string `json:"ip,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IPReference IPReference

// NewIPReference instantiates a new IPReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPReference() *IPReference {
	this := IPReference{}
	return &this
}

// NewIPReferenceWithDefaults instantiates a new IPReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPReferenceWithDefaults() *IPReference {
	this := IPReference{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IPReference) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPReference) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IPReference) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *IPReference) SetId(v int64) {
	o.Id = &v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *IPReference) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPReference) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *IPReference) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *IPReference) SetIp(v string) {
	o.Ip = &v
}

func (o IPReference) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IPReference) UnmarshalJSON(data []byte) (err error) {
	varIPReference := _IPReference{}

	err = json.Unmarshal(data, &varIPReference)

	if err != nil {
		return err
	}

	*o = IPReference(varIPReference)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "ip")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIPReference struct {
	value *IPReference
	isSet bool
}

func (v NullableIPReference) Get() *IPReference {
	return v.value
}

func (v *NullableIPReference) Set(val *IPReference) {
	v.value = val
	v.isSet = true
}

func (v NullableIPReference) IsSet() bool {
	return v.isSet
}

func (v *NullableIPReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPReference(val *IPReference) *NullableIPReference {
	return &NullableIPReference{value: val, isSet: true}
}

func (v NullableIPReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
