/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
	"fmt"
)

// checks if the Account type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Account{}

// Account struct for Account
type Account struct {
	// The unique ID of the account.
	Id      *int64           `json:"id,omitempty"`
	Company CompanyReference `json:"company"`
	// The name of the account.
	Name string `json:"name"`
	// The notes of the account.
	Notes *string     `json:"notes,omitempty"`
	Type  AccountType `json:"type"`
	// Account username.
	Username *string `json:"username,omitempty"`
	// Account password.
	Password *string `json:"password,omitempty"`
	// Account 2FA Secret Code.
	Var2faCode *string `json:"2faCode,omitempty"`
	// The number of the account.
	AccountNumber *string `json:"accountNumber,omitempty"`
	// The date the account expires.
	Expires *string `json:"expires,omitempty"`
	// A description of the account.
	Description *string `json:"description,omitempty"`
	// The email of the account.
	Email *string `json:"email,omitempty"`
	// A representative of the account.
	Representative *string `json:"representative,omitempty"`
	// A website of the account.
	AccountUrl *string `json:"accountUrl,omitempty"`
	// A tech telephone of the account.
	TechTelephone *string `json:"techTelephone,omitempty"`
	// A sales telephone of the account.
	SalesTelephone *string `json:"salesTelephone,omitempty"`
	ReviewBy       *User   `json:"reviewBy,omitempty"`
	// Review Due date
	DueDate *string  `json:"dueDate,omitempty"`
	Address *Address `json:"address,omitempty"`
	// The link of the account.
	Url *string `json:"url,omitempty"`
	// in (true)/out of service (false)
	InOut *bool `json:"inOut,omitempty"`
	// Reason - why this item is being \"checked out/marked inactive\"
	InOutNotes *string `json:"inOutNotes,omitempty"`
	// The date the account was most recently modified.
	Modified             *string `json:"modified,omitempty"`
	Sheets               []Sheet `json:"sheets,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Account Account

// NewAccount instantiates a new Account object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccount(company CompanyReference, name string, type_ AccountType) *Account {
	this := Account{}
	this.Company = company
	this.Name = name
	this.Type = type_
	return &this
}

// NewAccountWithDefaults instantiates a new Account object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountWithDefaults() *Account {
	this := Account{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Account) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Account) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *Account) SetId(v int64) {
	o.Id = &v
}

// GetCompany returns the Company field value
func (o *Account) GetCompany() CompanyReference {
	if o == nil {
		var ret CompanyReference
		return ret
	}

	return o.Company
}

// GetCompanyOk returns a tuple with the Company field value
// and a boolean to check if the value has been set.
func (o *Account) GetCompanyOk() (*CompanyReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Company, true
}

// SetCompany sets field value
func (o *Account) SetCompany(v CompanyReference) {
	o.Company = v
}

// GetName returns the Name field value
func (o *Account) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Account) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Account) SetName(v string) {
	o.Name = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *Account) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *Account) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *Account) SetNotes(v string) {
	o.Notes = &v
}

// GetType returns the Type field value
func (o *Account) GetType() AccountType {
	if o == nil {
		var ret AccountType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Account) GetTypeOk() (*AccountType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Account) SetType(v AccountType) {
	o.Type = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *Account) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *Account) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *Account) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *Account) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *Account) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *Account) SetPassword(v string) {
	o.Password = &v
}

// GetVar2faCode returns the Var2faCode field value if set, zero value otherwise.
func (o *Account) GetVar2faCode() string {
	if o == nil || IsNil(o.Var2faCode) {
		var ret string
		return ret
	}
	return *o.Var2faCode
}

// GetVar2faCodeOk returns a tuple with the Var2faCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetVar2faCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Var2faCode) {
		return nil, false
	}
	return o.Var2faCode, true
}

// HasVar2faCode returns a boolean if a field has been set.
func (o *Account) HasVar2faCode() bool {
	if o != nil && !IsNil(o.Var2faCode) {
		return true
	}

	return false
}

// SetVar2faCode gets a reference to the given string and assigns it to the Var2faCode field.
func (o *Account) SetVar2faCode(v string) {
	o.Var2faCode = &v
}

// GetAccountNumber returns the AccountNumber field value if set, zero value otherwise.
func (o *Account) GetAccountNumber() string {
	if o == nil || IsNil(o.AccountNumber) {
		var ret string
		return ret
	}
	return *o.AccountNumber
}

// GetAccountNumberOk returns a tuple with the AccountNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetAccountNumberOk() (*string, bool) {
	if o == nil || IsNil(o.AccountNumber) {
		return nil, false
	}
	return o.AccountNumber, true
}

// HasAccountNumber returns a boolean if a field has been set.
func (o *Account) HasAccountNumber() bool {
	if o != nil && !IsNil(o.AccountNumber) {
		return true
	}

	return false
}

// SetAccountNumber gets a reference to the given string and assigns it to the AccountNumber field.
func (o *Account) SetAccountNumber(v string) {
	o.AccountNumber = &v
}

// GetExpires returns the Expires field value if set, zero value otherwise.
func (o *Account) GetExpires() string {
	if o == nil || IsNil(o.Expires) {
		var ret string
		return ret
	}
	return *o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetExpiresOk() (*string, bool) {
	if o == nil || IsNil(o.Expires) {
		return nil, false
	}
	return o.Expires, true
}

// HasExpires returns a boolean if a field has been set.
func (o *Account) HasExpires() bool {
	if o != nil && !IsNil(o.Expires) {
		return true
	}

	return false
}

// SetExpires gets a reference to the given string and assigns it to the Expires field.
func (o *Account) SetExpires(v string) {
	o.Expires = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Account) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Account) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Account) SetDescription(v string) {
	o.Description = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *Account) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *Account) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *Account) SetEmail(v string) {
	o.Email = &v
}

// GetRepresentative returns the Representative field value if set, zero value otherwise.
func (o *Account) GetRepresentative() string {
	if o == nil || IsNil(o.Representative) {
		var ret string
		return ret
	}
	return *o.Representative
}

// GetRepresentativeOk returns a tuple with the Representative field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetRepresentativeOk() (*string, bool) {
	if o == nil || IsNil(o.Representative) {
		return nil, false
	}
	return o.Representative, true
}

// HasRepresentative returns a boolean if a field has been set.
func (o *Account) HasRepresentative() bool {
	if o != nil && !IsNil(o.Representative) {
		return true
	}

	return false
}

// SetRepresentative gets a reference to the given string and assigns it to the Representative field.
func (o *Account) SetRepresentative(v string) {
	o.Representative = &v
}

// GetAccountUrl returns the AccountUrl field value if set, zero value otherwise.
func (o *Account) GetAccountUrl() string {
	if o == nil || IsNil(o.AccountUrl) {
		var ret string
		return ret
	}
	return *o.AccountUrl
}

// GetAccountUrlOk returns a tuple with the AccountUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetAccountUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AccountUrl) {
		return nil, false
	}
	return o.AccountUrl, true
}

// HasAccountUrl returns a boolean if a field has been set.
func (o *Account) HasAccountUrl() bool {
	if o != nil && !IsNil(o.AccountUrl) {
		return true
	}

	return false
}

// SetAccountUrl gets a reference to the given string and assigns it to the AccountUrl field.
func (o *Account) SetAccountUrl(v string) {
	o.AccountUrl = &v
}

// GetTechTelephone returns the TechTelephone field value if set, zero value otherwise.
func (o *Account) GetTechTelephone() string {
	if o == nil || IsNil(o.TechTelephone) {
		var ret string
		return ret
	}
	return *o.TechTelephone
}

// GetTechTelephoneOk returns a tuple with the TechTelephone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetTechTelephoneOk() (*string, bool) {
	if o == nil || IsNil(o.TechTelephone) {
		return nil, false
	}
	return o.TechTelephone, true
}

// HasTechTelephone returns a boolean if a field has been set.
func (o *Account) HasTechTelephone() bool {
	if o != nil && !IsNil(o.TechTelephone) {
		return true
	}

	return false
}

// SetTechTelephone gets a reference to the given string and assigns it to the TechTelephone field.
func (o *Account) SetTechTelephone(v string) {
	o.TechTelephone = &v
}

// GetSalesTelephone returns the SalesTelephone field value if set, zero value otherwise.
func (o *Account) GetSalesTelephone() string {
	if o == nil || IsNil(o.SalesTelephone) {
		var ret string
		return ret
	}
	return *o.SalesTelephone
}

// GetSalesTelephoneOk returns a tuple with the SalesTelephone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetSalesTelephoneOk() (*string, bool) {
	if o == nil || IsNil(o.SalesTelephone) {
		return nil, false
	}
	return o.SalesTelephone, true
}

// HasSalesTelephone returns a boolean if a field has been set.
func (o *Account) HasSalesTelephone() bool {
	if o != nil && !IsNil(o.SalesTelephone) {
		return true
	}

	return false
}

// SetSalesTelephone gets a reference to the given string and assigns it to the SalesTelephone field.
func (o *Account) SetSalesTelephone(v string) {
	o.SalesTelephone = &v
}

// GetReviewBy returns the ReviewBy field value if set, zero value otherwise.
func (o *Account) GetReviewBy() User {
	if o == nil || IsNil(o.ReviewBy) {
		var ret User
		return ret
	}
	return *o.ReviewBy
}

// GetReviewByOk returns a tuple with the ReviewBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetReviewByOk() (*User, bool) {
	if o == nil || IsNil(o.ReviewBy) {
		return nil, false
	}
	return o.ReviewBy, true
}

// HasReviewBy returns a boolean if a field has been set.
func (o *Account) HasReviewBy() bool {
	if o != nil && !IsNil(o.ReviewBy) {
		return true
	}

	return false
}

// SetReviewBy gets a reference to the given User and assigns it to the ReviewBy field.
func (o *Account) SetReviewBy(v User) {
	o.ReviewBy = &v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *Account) GetDueDate() string {
	if o == nil || IsNil(o.DueDate) {
		var ret string
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetDueDateOk() (*string, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *Account) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given string and assigns it to the DueDate field.
func (o *Account) SetDueDate(v string) {
	o.DueDate = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *Account) GetAddress() Address {
	if o == nil || IsNil(o.Address) {
		var ret Address
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetAddressOk() (*Address, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *Account) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given Address and assigns it to the Address field.
func (o *Account) SetAddress(v Address) {
	o.Address = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Account) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Account) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Account) SetUrl(v string) {
	o.Url = &v
}

// GetInOut returns the InOut field value if set, zero value otherwise.
func (o *Account) GetInOut() bool {
	if o == nil || IsNil(o.InOut) {
		var ret bool
		return ret
	}
	return *o.InOut
}

// GetInOutOk returns a tuple with the InOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetInOutOk() (*bool, bool) {
	if o == nil || IsNil(o.InOut) {
		return nil, false
	}
	return o.InOut, true
}

// HasInOut returns a boolean if a field has been set.
func (o *Account) HasInOut() bool {
	if o != nil && !IsNil(o.InOut) {
		return true
	}

	return false
}

// SetInOut gets a reference to the given bool and assigns it to the InOut field.
func (o *Account) SetInOut(v bool) {
	o.InOut = &v
}

// GetInOutNotes returns the InOutNotes field value if set, zero value otherwise.
func (o *Account) GetInOutNotes() string {
	if o == nil || IsNil(o.InOutNotes) {
		var ret string
		return ret
	}
	return *o.InOutNotes
}

// GetInOutNotesOk returns a tuple with the InOutNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetInOutNotesOk() (*string, bool) {
	if o == nil || IsNil(o.InOutNotes) {
		return nil, false
	}
	return o.InOutNotes, true
}

// HasInOutNotes returns a boolean if a field has been set.
func (o *Account) HasInOutNotes() bool {
	if o != nil && !IsNil(o.InOutNotes) {
		return true
	}

	return false
}

// SetInOutNotes gets a reference to the given string and assigns it to the InOutNotes field.
func (o *Account) SetInOutNotes(v string) {
	o.InOutNotes = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *Account) GetModified() string {
	if o == nil || IsNil(o.Modified) {
		var ret string
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetModifiedOk() (*string, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *Account) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given string and assigns it to the Modified field.
func (o *Account) SetModified(v string) {
	o.Modified = &v
}

// GetSheets returns the Sheets field value if set, zero value otherwise.
func (o *Account) GetSheets() []Sheet {
	if o == nil || IsNil(o.Sheets) {
		var ret []Sheet
		return ret
	}
	return o.Sheets
}

// GetSheetsOk returns a tuple with the Sheets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetSheetsOk() ([]Sheet, bool) {
	if o == nil || IsNil(o.Sheets) {
		return nil, false
	}
	return o.Sheets, true
}

// HasSheets returns a boolean if a field has been set.
func (o *Account) HasSheets() bool {
	if o != nil && !IsNil(o.Sheets) {
		return true
	}

	return false
}

// SetSheets gets a reference to the given []Sheet and assigns it to the Sheets field.
func (o *Account) SetSheets(v []Sheet) {
	o.Sheets = v
}

func (o Account) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Account) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["company"] = o.Company
	toSerialize["name"] = o.Name
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Var2faCode) {
		toSerialize["2faCode"] = o.Var2faCode
	}
	if !IsNil(o.AccountNumber) {
		toSerialize["accountNumber"] = o.AccountNumber
	}
	if !IsNil(o.Expires) {
		toSerialize["expires"] = o.Expires
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Representative) {
		toSerialize["representative"] = o.Representative
	}
	if !IsNil(o.AccountUrl) {
		toSerialize["accountUrl"] = o.AccountUrl
	}
	if !IsNil(o.TechTelephone) {
		toSerialize["techTelephone"] = o.TechTelephone
	}
	if !IsNil(o.SalesTelephone) {
		toSerialize["salesTelephone"] = o.SalesTelephone
	}
	if !IsNil(o.ReviewBy) {
		toSerialize["reviewBy"] = o.ReviewBy
	}
	if !IsNil(o.DueDate) {
		toSerialize["dueDate"] = o.DueDate
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.InOut) {
		toSerialize["inOut"] = o.InOut
	}
	if !IsNil(o.InOutNotes) {
		toSerialize["inOutNotes"] = o.InOutNotes
	}
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	if !IsNil(o.Sheets) {
		toSerialize["sheets"] = o.Sheets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Account) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"company",
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccount := _Account{}

	err = json.Unmarshal(data, &varAccount)

	if err != nil {
		return err
	}

	*o = Account(varAccount)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "company")
		delete(additionalProperties, "name")
		delete(additionalProperties, "notes")
		delete(additionalProperties, "type")
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		delete(additionalProperties, "2faCode")
		delete(additionalProperties, "accountNumber")
		delete(additionalProperties, "expires")
		delete(additionalProperties, "description")
		delete(additionalProperties, "email")
		delete(additionalProperties, "representative")
		delete(additionalProperties, "accountUrl")
		delete(additionalProperties, "techTelephone")
		delete(additionalProperties, "salesTelephone")
		delete(additionalProperties, "reviewBy")
		delete(additionalProperties, "dueDate")
		delete(additionalProperties, "address")
		delete(additionalProperties, "url")
		delete(additionalProperties, "inOut")
		delete(additionalProperties, "inOutNotes")
		delete(additionalProperties, "modified")
		delete(additionalProperties, "sheets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccount struct {
	value *Account
	isSet bool
}

func (v NullableAccount) Get() *Account {
	return v.value
}

func (v *NullableAccount) Set(val *Account) {
	v.value = val
	v.isSet = true
}

func (v NullableAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccount(val *Account) *NullableAccount {
	return &NullableAccount{value: val, isSet: true}
}

func (v NullableAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
