/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the CabinetReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CabinetReference{}

// CabinetReference struct for CabinetReference
type CabinetReference struct {
	// The unique ID of the cabinet.
	Id *int64 `json:"id,omitempty"`
	// The name of the cabinet.
	Name                 *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CabinetReference CabinetReference

// NewCabinetReference instantiates a new CabinetReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCabinetReference() *CabinetReference {
	this := CabinetReference{}
	return &this
}

// NewCabinetReferenceWithDefaults instantiates a new CabinetReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCabinetReferenceWithDefaults() *CabinetReference {
	this := CabinetReference{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CabinetReference) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CabinetReference) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CabinetReference) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *CabinetReference) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CabinetReference) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CabinetReference) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CabinetReference) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CabinetReference) SetName(v string) {
	o.Name = &v
}

func (o CabinetReference) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CabinetReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CabinetReference) UnmarshalJSON(data []byte) (err error) {
	varCabinetReference := _CabinetReference{}

	err = json.Unmarshal(data, &varCabinetReference)

	if err != nil {
		return err
	}

	*o = CabinetReference(varCabinetReference)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCabinetReference struct {
	value *CabinetReference
	isSet bool
}

func (v NullableCabinetReference) Get() *CabinetReference {
	return v.value
}

func (v *NullableCabinetReference) Set(val *CabinetReference) {
	v.value = val
	v.isSet = true
}

func (v NullableCabinetReference) IsSet() bool {
	return v.isSet
}

func (v *NullableCabinetReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCabinetReference(val *CabinetReference) *NullableCabinetReference {
	return &NullableCabinetReference{value: val, isSet: true}
}

func (v NullableCabinetReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCabinetReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
