/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
	"fmt"
)

// checks if the MUrl type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MUrl{}

// MUrl struct for MUrl
type MUrl struct {
	// The unique ID of the Management Url.
	Id *int64 `json:"id,omitempty"`
	// Title
	Title string `json:"title"`
	// URL
	Url string `json:"url"`
	// Notes
	Notes *string `json:"notes,omitempty"`
	// Only one URL can be Default
	Preferred            bool `json:"preferred"`
	AdditionalProperties map[string]interface{}
}

type _MUrl MUrl

// NewMUrl instantiates a new MUrl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMUrl(title string, url string, preferred bool) *MUrl {
	this := MUrl{}
	this.Title = title
	this.Url = url
	this.Preferred = preferred
	return &this
}

// NewMUrlWithDefaults instantiates a new MUrl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMUrlWithDefaults() *MUrl {
	this := MUrl{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MUrl) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MUrl) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MUrl) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *MUrl) SetId(v int64) {
	o.Id = &v
}

// GetTitle returns the Title field value
func (o *MUrl) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *MUrl) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *MUrl) SetTitle(v string) {
	o.Title = v
}

// GetUrl returns the Url field value
func (o *MUrl) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *MUrl) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *MUrl) SetUrl(v string) {
	o.Url = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *MUrl) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MUrl) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *MUrl) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *MUrl) SetNotes(v string) {
	o.Notes = &v
}

// GetPreferred returns the Preferred field value
func (o *MUrl) GetPreferred() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Preferred
}

// GetPreferredOk returns a tuple with the Preferred field value
// and a boolean to check if the value has been set.
func (o *MUrl) GetPreferredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Preferred, true
}

// SetPreferred sets field value
func (o *MUrl) SetPreferred(v bool) {
	o.Preferred = v
}

func (o MUrl) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MUrl) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["title"] = o.Title
	toSerialize["url"] = o.Url
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	toSerialize["preferred"] = o.Preferred

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MUrl) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"url",
		"preferred",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMUrl := _MUrl{}

	err = json.Unmarshal(data, &varMUrl)

	if err != nil {
		return err
	}

	*o = MUrl(varMUrl)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "title")
		delete(additionalProperties, "url")
		delete(additionalProperties, "notes")
		delete(additionalProperties, "preferred")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMUrl struct {
	value *MUrl
	isSet bool
}

func (v NullableMUrl) Get() *MUrl {
	return v.value
}

func (v *NullableMUrl) Set(val *MUrl) {
	v.value = val
	v.isSet = true
}

func (v NullableMUrl) IsSet() bool {
	return v.isSet
}

func (v *NullableMUrl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMUrl(val *MUrl) *NullableMUrl {
	return &NullableMUrl{value: val, isSet: true}
}

func (v NullableMUrl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMUrl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
