/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Configuration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Configuration{}

// Configuration struct for Configuration
type Configuration struct {
	// The unique ID of the configuration.
	Id      *int64           `json:"id,omitempty"`
	Company CompanyReference `json:"company"`
	// The name of the configuration.
	Name string `json:"name"`
	// The notes of the configuration.
	Notes *string           `json:"notes,omitempty"`
	Type  ConfigurationType `json:"type"`
	// A description of the configuration.
	Description *string          `json:"description,omitempty"`
	Device      *DeviceReference `json:"device,omitempty"`
	// The URI/Path of the configuration.
	UriPath *string `json:"uriPath,omitempty"`
	// The date the configuration has been installed.
	InstallDate *string `json:"installDate,omitempty"`
	// The date the configuration expires.
	DateExpires *string `json:"dateExpires,omitempty"`
	ReviewBy    *User   `json:"reviewBy,omitempty"`
	// Review Due date
	DueDate *string `json:"dueDate,omitempty"`
	// The foreign id of the synced integration.
	ForeignId *int64 `json:"foreignId,omitempty"`
	// The foreign type of the synced integration.
	ForeignType *string `json:"foreignType,omitempty"`
	// The link of the configuration.
	Url *string `json:"url,omitempty"`
	// in (true)/out of service (false)
	InOut *bool `json:"inOut,omitempty"`
	// Reason - why this item is being \"checked out/marked inactive\"
	InOutNotes *string `json:"inOutNotes,omitempty"`
	// The date the configuration was most recently modified.
	Modified             *time.Time `json:"modified,omitempty"`
	Sheets               *Sheet     `json:"sheets,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Configuration Configuration

// NewConfiguration instantiates a new Configuration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfiguration(company CompanyReference, name string, type_ ConfigurationType) *Configuration {
	this := Configuration{}
	this.Company = company
	this.Name = name
	this.Type = type_
	return &this
}

// NewConfigurationWithDefaults instantiates a new Configuration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationWithDefaults() *Configuration {
	this := Configuration{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Configuration) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Configuration) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *Configuration) SetId(v int64) {
	o.Id = &v
}

// GetCompany returns the Company field value
func (o *Configuration) GetCompany() CompanyReference {
	if o == nil {
		var ret CompanyReference
		return ret
	}

	return o.Company
}

// GetCompanyOk returns a tuple with the Company field value
// and a boolean to check if the value has been set.
func (o *Configuration) GetCompanyOk() (*CompanyReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Company, true
}

// SetCompany sets field value
func (o *Configuration) SetCompany(v CompanyReference) {
	o.Company = v
}

// GetName returns the Name field value
func (o *Configuration) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Configuration) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Configuration) SetName(v string) {
	o.Name = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *Configuration) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *Configuration) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *Configuration) SetNotes(v string) {
	o.Notes = &v
}

// GetType returns the Type field value
func (o *Configuration) GetType() ConfigurationType {
	if o == nil {
		var ret ConfigurationType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Configuration) GetTypeOk() (*ConfigurationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Configuration) SetType(v ConfigurationType) {
	o.Type = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Configuration) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Configuration) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Configuration) SetDescription(v string) {
	o.Description = &v
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *Configuration) GetDevice() DeviceReference {
	if o == nil || IsNil(o.Device) {
		var ret DeviceReference
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetDeviceOk() (*DeviceReference, bool) {
	if o == nil || IsNil(o.Device) {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *Configuration) HasDevice() bool {
	if o != nil && !IsNil(o.Device) {
		return true
	}

	return false
}

// SetDevice gets a reference to the given DeviceReference and assigns it to the Device field.
func (o *Configuration) SetDevice(v DeviceReference) {
	o.Device = &v
}

// GetUriPath returns the UriPath field value if set, zero value otherwise.
func (o *Configuration) GetUriPath() string {
	if o == nil || IsNil(o.UriPath) {
		var ret string
		return ret
	}
	return *o.UriPath
}

// GetUriPathOk returns a tuple with the UriPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetUriPathOk() (*string, bool) {
	if o == nil || IsNil(o.UriPath) {
		return nil, false
	}
	return o.UriPath, true
}

// HasUriPath returns a boolean if a field has been set.
func (o *Configuration) HasUriPath() bool {
	if o != nil && !IsNil(o.UriPath) {
		return true
	}

	return false
}

// SetUriPath gets a reference to the given string and assigns it to the UriPath field.
func (o *Configuration) SetUriPath(v string) {
	o.UriPath = &v
}

// GetInstallDate returns the InstallDate field value if set, zero value otherwise.
func (o *Configuration) GetInstallDate() string {
	if o == nil || IsNil(o.InstallDate) {
		var ret string
		return ret
	}
	return *o.InstallDate
}

// GetInstallDateOk returns a tuple with the InstallDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetInstallDateOk() (*string, bool) {
	if o == nil || IsNil(o.InstallDate) {
		return nil, false
	}
	return o.InstallDate, true
}

// HasInstallDate returns a boolean if a field has been set.
func (o *Configuration) HasInstallDate() bool {
	if o != nil && !IsNil(o.InstallDate) {
		return true
	}

	return false
}

// SetInstallDate gets a reference to the given string and assigns it to the InstallDate field.
func (o *Configuration) SetInstallDate(v string) {
	o.InstallDate = &v
}

// GetDateExpires returns the DateExpires field value if set, zero value otherwise.
func (o *Configuration) GetDateExpires() string {
	if o == nil || IsNil(o.DateExpires) {
		var ret string
		return ret
	}
	return *o.DateExpires
}

// GetDateExpiresOk returns a tuple with the DateExpires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetDateExpiresOk() (*string, bool) {
	if o == nil || IsNil(o.DateExpires) {
		return nil, false
	}
	return o.DateExpires, true
}

// HasDateExpires returns a boolean if a field has been set.
func (o *Configuration) HasDateExpires() bool {
	if o != nil && !IsNil(o.DateExpires) {
		return true
	}

	return false
}

// SetDateExpires gets a reference to the given string and assigns it to the DateExpires field.
func (o *Configuration) SetDateExpires(v string) {
	o.DateExpires = &v
}

// GetReviewBy returns the ReviewBy field value if set, zero value otherwise.
func (o *Configuration) GetReviewBy() User {
	if o == nil || IsNil(o.ReviewBy) {
		var ret User
		return ret
	}
	return *o.ReviewBy
}

// GetReviewByOk returns a tuple with the ReviewBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetReviewByOk() (*User, bool) {
	if o == nil || IsNil(o.ReviewBy) {
		return nil, false
	}
	return o.ReviewBy, true
}

// HasReviewBy returns a boolean if a field has been set.
func (o *Configuration) HasReviewBy() bool {
	if o != nil && !IsNil(o.ReviewBy) {
		return true
	}

	return false
}

// SetReviewBy gets a reference to the given User and assigns it to the ReviewBy field.
func (o *Configuration) SetReviewBy(v User) {
	o.ReviewBy = &v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *Configuration) GetDueDate() string {
	if o == nil || IsNil(o.DueDate) {
		var ret string
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetDueDateOk() (*string, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *Configuration) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given string and assigns it to the DueDate field.
func (o *Configuration) SetDueDate(v string) {
	o.DueDate = &v
}

// GetForeignId returns the ForeignId field value if set, zero value otherwise.
func (o *Configuration) GetForeignId() int64 {
	if o == nil || IsNil(o.ForeignId) {
		var ret int64
		return ret
	}
	return *o.ForeignId
}

// GetForeignIdOk returns a tuple with the ForeignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetForeignIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ForeignId) {
		return nil, false
	}
	return o.ForeignId, true
}

// HasForeignId returns a boolean if a field has been set.
func (o *Configuration) HasForeignId() bool {
	if o != nil && !IsNil(o.ForeignId) {
		return true
	}

	return false
}

// SetForeignId gets a reference to the given int64 and assigns it to the ForeignId field.
func (o *Configuration) SetForeignId(v int64) {
	o.ForeignId = &v
}

// GetForeignType returns the ForeignType field value if set, zero value otherwise.
func (o *Configuration) GetForeignType() string {
	if o == nil || IsNil(o.ForeignType) {
		var ret string
		return ret
	}
	return *o.ForeignType
}

// GetForeignTypeOk returns a tuple with the ForeignType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetForeignTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ForeignType) {
		return nil, false
	}
	return o.ForeignType, true
}

// HasForeignType returns a boolean if a field has been set.
func (o *Configuration) HasForeignType() bool {
	if o != nil && !IsNil(o.ForeignType) {
		return true
	}

	return false
}

// SetForeignType gets a reference to the given string and assigns it to the ForeignType field.
func (o *Configuration) SetForeignType(v string) {
	o.ForeignType = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Configuration) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Configuration) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Configuration) SetUrl(v string) {
	o.Url = &v
}

// GetInOut returns the InOut field value if set, zero value otherwise.
func (o *Configuration) GetInOut() bool {
	if o == nil || IsNil(o.InOut) {
		var ret bool
		return ret
	}
	return *o.InOut
}

// GetInOutOk returns a tuple with the InOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetInOutOk() (*bool, bool) {
	if o == nil || IsNil(o.InOut) {
		return nil, false
	}
	return o.InOut, true
}

// HasInOut returns a boolean if a field has been set.
func (o *Configuration) HasInOut() bool {
	if o != nil && !IsNil(o.InOut) {
		return true
	}

	return false
}

// SetInOut gets a reference to the given bool and assigns it to the InOut field.
func (o *Configuration) SetInOut(v bool) {
	o.InOut = &v
}

// GetInOutNotes returns the InOutNotes field value if set, zero value otherwise.
func (o *Configuration) GetInOutNotes() string {
	if o == nil || IsNil(o.InOutNotes) {
		var ret string
		return ret
	}
	return *o.InOutNotes
}

// GetInOutNotesOk returns a tuple with the InOutNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetInOutNotesOk() (*string, bool) {
	if o == nil || IsNil(o.InOutNotes) {
		return nil, false
	}
	return o.InOutNotes, true
}

// HasInOutNotes returns a boolean if a field has been set.
func (o *Configuration) HasInOutNotes() bool {
	if o != nil && !IsNil(o.InOutNotes) {
		return true
	}

	return false
}

// SetInOutNotes gets a reference to the given string and assigns it to the InOutNotes field.
func (o *Configuration) SetInOutNotes(v string) {
	o.InOutNotes = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *Configuration) GetModified() time.Time {
	if o == nil || IsNil(o.Modified) {
		var ret time.Time
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *Configuration) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given time.Time and assigns it to the Modified field.
func (o *Configuration) SetModified(v time.Time) {
	o.Modified = &v
}

// GetSheets returns the Sheets field value if set, zero value otherwise.
func (o *Configuration) GetSheets() Sheet {
	if o == nil || IsNil(o.Sheets) {
		var ret Sheet
		return ret
	}
	return *o.Sheets
}

// GetSheetsOk returns a tuple with the Sheets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configuration) GetSheetsOk() (*Sheet, bool) {
	if o == nil || IsNil(o.Sheets) {
		return nil, false
	}
	return o.Sheets, true
}

// HasSheets returns a boolean if a field has been set.
func (o *Configuration) HasSheets() bool {
	if o != nil && !IsNil(o.Sheets) {
		return true
	}

	return false
}

// SetSheets gets a reference to the given Sheet and assigns it to the Sheets field.
func (o *Configuration) SetSheets(v Sheet) {
	o.Sheets = &v
}

func (o Configuration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Configuration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["company"] = o.Company
	toSerialize["name"] = o.Name
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Device) {
		toSerialize["device"] = o.Device
	}
	if !IsNil(o.UriPath) {
		toSerialize["uriPath"] = o.UriPath
	}
	if !IsNil(o.InstallDate) {
		toSerialize["installDate"] = o.InstallDate
	}
	if !IsNil(o.DateExpires) {
		toSerialize["dateExpires"] = o.DateExpires
	}
	if !IsNil(o.ReviewBy) {
		toSerialize["reviewBy"] = o.ReviewBy
	}
	if !IsNil(o.DueDate) {
		toSerialize["dueDate"] = o.DueDate
	}
	if !IsNil(o.ForeignId) {
		toSerialize["foreignId"] = o.ForeignId
	}
	if !IsNil(o.ForeignType) {
		toSerialize["foreignType"] = o.ForeignType
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.InOut) {
		toSerialize["inOut"] = o.InOut
	}
	if !IsNil(o.InOutNotes) {
		toSerialize["inOutNotes"] = o.InOutNotes
	}
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	if !IsNil(o.Sheets) {
		toSerialize["sheets"] = o.Sheets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Configuration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"company",
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfiguration := _Configuration{}

	err = json.Unmarshal(data, &varConfiguration)

	if err != nil {
		return err
	}

	*o = Configuration(varConfiguration)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "company")
		delete(additionalProperties, "name")
		delete(additionalProperties, "notes")
		delete(additionalProperties, "type")
		delete(additionalProperties, "description")
		delete(additionalProperties, "device")
		delete(additionalProperties, "uriPath")
		delete(additionalProperties, "installDate")
		delete(additionalProperties, "dateExpires")
		delete(additionalProperties, "reviewBy")
		delete(additionalProperties, "dueDate")
		delete(additionalProperties, "foreignId")
		delete(additionalProperties, "foreignType")
		delete(additionalProperties, "url")
		delete(additionalProperties, "inOut")
		delete(additionalProperties, "inOutNotes")
		delete(additionalProperties, "modified")
		delete(additionalProperties, "sheets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfiguration struct {
	value *Configuration
	isSet bool
}

func (v NullableConfiguration) Get() *Configuration {
	return v.value
}

func (v *NullableConfiguration) Set(val *Configuration) {
	v.value = val
	v.isSet = true
}

func (v NullableConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfiguration(val *Configuration) *NullableConfiguration {
	return &NullableConfiguration{value: val, isSet: true}
}

func (v NullableConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
