/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the IPPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPPatch{}

// IPPatch struct for IPPatch
type IPPatch struct {
	// IP Address
	Ip *string `json:"ip,omitempty"`
	// Mac Address
	Mac *string `json:"mac,omitempty"`
	// Description
	Description          *string                  `json:"description,omitempty"`
	IpNetwork            *IPNetworkReferencePatch `json:"ipNetwork,omitempty"`
	SwitchPort           *SwitchPortReference     `json:"switchPort,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IPPatch IPPatch

// NewIPPatch instantiates a new IPPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPPatch() *IPPatch {
	this := IPPatch{}
	return &this
}

// NewIPPatchWithDefaults instantiates a new IPPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPPatchWithDefaults() *IPPatch {
	this := IPPatch{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *IPPatch) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPPatch) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *IPPatch) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *IPPatch) SetIp(v string) {
	o.Ip = &v
}

// GetMac returns the Mac field value if set, zero value otherwise.
func (o *IPPatch) GetMac() string {
	if o == nil || IsNil(o.Mac) {
		var ret string
		return ret
	}
	return *o.Mac
}

// GetMacOk returns a tuple with the Mac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPPatch) GetMacOk() (*string, bool) {
	if o == nil || IsNil(o.Mac) {
		return nil, false
	}
	return o.Mac, true
}

// HasMac returns a boolean if a field has been set.
func (o *IPPatch) HasMac() bool {
	if o != nil && !IsNil(o.Mac) {
		return true
	}

	return false
}

// SetMac gets a reference to the given string and assigns it to the Mac field.
func (o *IPPatch) SetMac(v string) {
	o.Mac = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *IPPatch) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPPatch) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *IPPatch) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *IPPatch) SetDescription(v string) {
	o.Description = &v
}

// GetIpNetwork returns the IpNetwork field value if set, zero value otherwise.
func (o *IPPatch) GetIpNetwork() IPNetworkReferencePatch {
	if o == nil || IsNil(o.IpNetwork) {
		var ret IPNetworkReferencePatch
		return ret
	}
	return *o.IpNetwork
}

// GetIpNetworkOk returns a tuple with the IpNetwork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPPatch) GetIpNetworkOk() (*IPNetworkReferencePatch, bool) {
	if o == nil || IsNil(o.IpNetwork) {
		return nil, false
	}
	return o.IpNetwork, true
}

// HasIpNetwork returns a boolean if a field has been set.
func (o *IPPatch) HasIpNetwork() bool {
	if o != nil && !IsNil(o.IpNetwork) {
		return true
	}

	return false
}

// SetIpNetwork gets a reference to the given IPNetworkReferencePatch and assigns it to the IpNetwork field.
func (o *IPPatch) SetIpNetwork(v IPNetworkReferencePatch) {
	o.IpNetwork = &v
}

// GetSwitchPort returns the SwitchPort field value if set, zero value otherwise.
func (o *IPPatch) GetSwitchPort() SwitchPortReference {
	if o == nil || IsNil(o.SwitchPort) {
		var ret SwitchPortReference
		return ret
	}
	return *o.SwitchPort
}

// GetSwitchPortOk returns a tuple with the SwitchPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPPatch) GetSwitchPortOk() (*SwitchPortReference, bool) {
	if o == nil || IsNil(o.SwitchPort) {
		return nil, false
	}
	return o.SwitchPort, true
}

// HasSwitchPort returns a boolean if a field has been set.
func (o *IPPatch) HasSwitchPort() bool {
	if o != nil && !IsNil(o.SwitchPort) {
		return true
	}

	return false
}

// SetSwitchPort gets a reference to the given SwitchPortReference and assigns it to the SwitchPort field.
func (o *IPPatch) SetSwitchPort(v SwitchPortReference) {
	o.SwitchPort = &v
}

func (o IPPatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Mac) {
		toSerialize["mac"] = o.Mac
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IpNetwork) {
		toSerialize["ipNetwork"] = o.IpNetwork
	}
	if !IsNil(o.SwitchPort) {
		toSerialize["switchPort"] = o.SwitchPort
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IPPatch) UnmarshalJSON(data []byte) (err error) {
	varIPPatch := _IPPatch{}

	err = json.Unmarshal(data, &varIPPatch)

	if err != nil {
		return err
	}

	*o = IPPatch(varIPPatch)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ip")
		delete(additionalProperties, "mac")
		delete(additionalProperties, "description")
		delete(additionalProperties, "ipNetwork")
		delete(additionalProperties, "switchPort")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIPPatch struct {
	value *IPPatch
	isSet bool
}

func (v NullableIPPatch) Get() *IPPatch {
	return v.value
}

func (v *NullableIPPatch) Set(val *IPPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableIPPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableIPPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPPatch(val *IPPatch) *NullableIPPatch {
	return &NullableIPPatch{value: val, isSet: true}
}

func (v NullableIPPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
