/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the Sheet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Sheet{}

// Sheet struct for Sheet
type Sheet struct {
	// The id of the sheet field.
	Id *string `json:"id,omitempty"`
	// The name of the sheet field.
	Name *string `json:"name,omitempty"`
	// The description of the sheet field.
	Description *string `json:"description,omitempty"`
	// The modifiydate of the sheet field.
	Modified *string `json:"modified,omitempty"`
	// The submitdate of the sheet field.
	Submitdate *string `json:"submitdate,omitempty"`
	// The submittime of the sheet field.
	Submittime *string `json:"submittime,omitempty"`
	// get Sheet API URL
	Sheeturl             *string `json:"sheeturl,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Sheet Sheet

// NewSheet instantiates a new Sheet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSheet() *Sheet {
	this := Sheet{}
	return &this
}

// NewSheetWithDefaults instantiates a new Sheet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSheetWithDefaults() *Sheet {
	this := Sheet{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Sheet) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sheet) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Sheet) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Sheet) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Sheet) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sheet) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Sheet) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Sheet) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Sheet) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sheet) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Sheet) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Sheet) SetDescription(v string) {
	o.Description = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *Sheet) GetModified() string {
	if o == nil || IsNil(o.Modified) {
		var ret string
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sheet) GetModifiedOk() (*string, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *Sheet) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given string and assigns it to the Modified field.
func (o *Sheet) SetModified(v string) {
	o.Modified = &v
}

// GetSubmitdate returns the Submitdate field value if set, zero value otherwise.
func (o *Sheet) GetSubmitdate() string {
	if o == nil || IsNil(o.Submitdate) {
		var ret string
		return ret
	}
	return *o.Submitdate
}

// GetSubmitdateOk returns a tuple with the Submitdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sheet) GetSubmitdateOk() (*string, bool) {
	if o == nil || IsNil(o.Submitdate) {
		return nil, false
	}
	return o.Submitdate, true
}

// HasSubmitdate returns a boolean if a field has been set.
func (o *Sheet) HasSubmitdate() bool {
	if o != nil && !IsNil(o.Submitdate) {
		return true
	}

	return false
}

// SetSubmitdate gets a reference to the given string and assigns it to the Submitdate field.
func (o *Sheet) SetSubmitdate(v string) {
	o.Submitdate = &v
}

// GetSubmittime returns the Submittime field value if set, zero value otherwise.
func (o *Sheet) GetSubmittime() string {
	if o == nil || IsNil(o.Submittime) {
		var ret string
		return ret
	}
	return *o.Submittime
}

// GetSubmittimeOk returns a tuple with the Submittime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sheet) GetSubmittimeOk() (*string, bool) {
	if o == nil || IsNil(o.Submittime) {
		return nil, false
	}
	return o.Submittime, true
}

// HasSubmittime returns a boolean if a field has been set.
func (o *Sheet) HasSubmittime() bool {
	if o != nil && !IsNil(o.Submittime) {
		return true
	}

	return false
}

// SetSubmittime gets a reference to the given string and assigns it to the Submittime field.
func (o *Sheet) SetSubmittime(v string) {
	o.Submittime = &v
}

// GetSheeturl returns the Sheeturl field value if set, zero value otherwise.
func (o *Sheet) GetSheeturl() string {
	if o == nil || IsNil(o.Sheeturl) {
		var ret string
		return ret
	}
	return *o.Sheeturl
}

// GetSheeturlOk returns a tuple with the Sheeturl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sheet) GetSheeturlOk() (*string, bool) {
	if o == nil || IsNil(o.Sheeturl) {
		return nil, false
	}
	return o.Sheeturl, true
}

// HasSheeturl returns a boolean if a field has been set.
func (o *Sheet) HasSheeturl() bool {
	if o != nil && !IsNil(o.Sheeturl) {
		return true
	}

	return false
}

// SetSheeturl gets a reference to the given string and assigns it to the Sheeturl field.
func (o *Sheet) SetSheeturl(v string) {
	o.Sheeturl = &v
}

func (o Sheet) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Sheet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	if !IsNil(o.Submitdate) {
		toSerialize["submitdate"] = o.Submitdate
	}
	if !IsNil(o.Submittime) {
		toSerialize["submittime"] = o.Submittime
	}
	if !IsNil(o.Sheeturl) {
		toSerialize["sheeturl"] = o.Sheeturl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Sheet) UnmarshalJSON(data []byte) (err error) {
	varSheet := _Sheet{}

	err = json.Unmarshal(data, &varSheet)

	if err != nil {
		return err
	}

	*o = Sheet(varSheet)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "modified")
		delete(additionalProperties, "submitdate")
		delete(additionalProperties, "submittime")
		delete(additionalProperties, "sheeturl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSheet struct {
	value *Sheet
	isSet bool
}

func (v NullableSheet) Get() *Sheet {
	return v.value
}

func (v *NullableSheet) Set(val *Sheet) {
	v.value = val
	v.isSet = true
}

func (v NullableSheet) IsSet() bool {
	return v.isSet
}

func (v *NullableSheet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSheet(val *Sheet) *NullableSheet {
	return &NullableSheet{value: val, isSet: true}
}

func (v NullableSheet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSheet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
