/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the PreferredAccess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PreferredAccess{}

// PreferredAccess struct for PreferredAccess
type PreferredAccess struct {
	// IP address
	IpAddress *string `json:"ipAddress,omitempty"`
	// TCP Port
	TcpPort *string `json:"tcpPort,omitempty"`
	// Protocol
	Protocol             *string `json:"protocol,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PreferredAccess PreferredAccess

// NewPreferredAccess instantiates a new PreferredAccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreferredAccess() *PreferredAccess {
	this := PreferredAccess{}
	return &this
}

// NewPreferredAccessWithDefaults instantiates a new PreferredAccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreferredAccessWithDefaults() *PreferredAccess {
	this := PreferredAccess{}
	return &this
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise.
func (o *PreferredAccess) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress) {
		var ret string
		return ret
	}
	return *o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreferredAccess) GetIpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.IpAddress) {
		return nil, false
	}
	return o.IpAddress, true
}

// HasIpAddress returns a boolean if a field has been set.
func (o *PreferredAccess) HasIpAddress() bool {
	if o != nil && !IsNil(o.IpAddress) {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given string and assigns it to the IpAddress field.
func (o *PreferredAccess) SetIpAddress(v string) {
	o.IpAddress = &v
}

// GetTcpPort returns the TcpPort field value if set, zero value otherwise.
func (o *PreferredAccess) GetTcpPort() string {
	if o == nil || IsNil(o.TcpPort) {
		var ret string
		return ret
	}
	return *o.TcpPort
}

// GetTcpPortOk returns a tuple with the TcpPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreferredAccess) GetTcpPortOk() (*string, bool) {
	if o == nil || IsNil(o.TcpPort) {
		return nil, false
	}
	return o.TcpPort, true
}

// HasTcpPort returns a boolean if a field has been set.
func (o *PreferredAccess) HasTcpPort() bool {
	if o != nil && !IsNil(o.TcpPort) {
		return true
	}

	return false
}

// SetTcpPort gets a reference to the given string and assigns it to the TcpPort field.
func (o *PreferredAccess) SetTcpPort(v string) {
	o.TcpPort = &v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *PreferredAccess) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreferredAccess) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *PreferredAccess) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *PreferredAccess) SetProtocol(v string) {
	o.Protocol = &v
}

func (o PreferredAccess) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PreferredAccess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IpAddress) {
		toSerialize["ipAddress"] = o.IpAddress
	}
	if !IsNil(o.TcpPort) {
		toSerialize["tcpPort"] = o.TcpPort
	}
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PreferredAccess) UnmarshalJSON(data []byte) (err error) {
	varPreferredAccess := _PreferredAccess{}

	err = json.Unmarshal(data, &varPreferredAccess)

	if err != nil {
		return err
	}

	*o = PreferredAccess(varPreferredAccess)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ipAddress")
		delete(additionalProperties, "tcpPort")
		delete(additionalProperties, "protocol")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePreferredAccess struct {
	value *PreferredAccess
	isSet bool
}

func (v NullablePreferredAccess) Get() *PreferredAccess {
	return v.value
}

func (v *NullablePreferredAccess) Set(val *PreferredAccess) {
	v.value = val
	v.isSet = true
}

func (v NullablePreferredAccess) IsSet() bool {
	return v.isSet
}

func (v *NullablePreferredAccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreferredAccess(val *PreferredAccess) *NullablePreferredAccess {
	return &NullablePreferredAccess{value: val, isSet: true}
}

func (v NullablePreferredAccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreferredAccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
