/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
	"fmt"
)

// checks if the Device type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Device{}

// Device struct for Device
type Device struct {
	// The unique ID of the device.
	Id      *int64           `json:"id,omitempty"`
	Company CompanyReference `json:"company"`
	// Friendly Device Name.
	Name string `json:"name"`
	// Hostname.
	HostName string     `json:"hostName"`
	Type     DeviceType `json:"type"`
	// Device username.
	Username *string `json:"username,omitempty"`
	// Device password.
	Password *string `json:"password,omitempty"`
	// The description of the device.
	Description *string `json:"description,omitempty"`
	// Domain or Realm.
	Domain *string `json:"domain,omitempty"`
	// The physical location of the device.
	Location *string `json:"location,omitempty"`
	// Install Date
	InstallDate *string `json:"installDate,omitempty"`
	// Manufacturer
	Manufacturer *string `json:"manufacturer,omitempty"`
	// Model
	Model *string `json:"model,omitempty"`
	// IMEI
	Imei *string `json:"imei,omitempty"`
	// Serial
	Serial *string `json:"serial,omitempty"`
	// Tag
	Tag *string `json:"tag,omitempty"`
	// Purchase Price
	PurchasePrice *float32 `json:"purchasePrice,omitempty"`
	// Purchase Date
	PurchaseDate *string `json:"purchaseDate,omitempty"`
	// Configuration Text
	Configuration *string `json:"configuration,omitempty"`
	// Warranty Expires
	WarrantyExpires *string `json:"warrantyExpires,omitempty"`
	// Retire Date
	RetireDate *string `json:"retireDate,omitempty"`
	// Lease End Date
	LeaseEndDate *string `json:"leaseEndDate,omitempty"`
	// Leased or not
	Leased *bool `json:"leased,omitempty"`
	// The operational system of the device.
	Os *string `json:"os,omitempty"`
	// Build Number
	BuildNumber *string `json:"buildNumber,omitempty"`
	// Version
	Version *string `json:"version,omitempty"`
	// Service Pack.
	ServicePack *string `json:"servicePack,omitempty"`
	// CPU
	Cpu *string `json:"cpu,omitempty"`
	// Memory (MB)
	Memory *int32 `json:"memory,omitempty"`
	// HardDisk Info
	HardDiskInfo *string `json:"hardDiskInfo,omitempty"`
	// Raid Controller
	RaidController *string `json:"raidController,omitempty"`
	// SCSI Controller
	ScsiController *string `json:"scsiController,omitempty"`
	// Number of Sockets
	NumberCpu *int32 `json:"numberCpu,omitempty"`
	// The product key of the device.
	ProductKey       *string            `json:"productKey,omitempty"`
	LastLoggedInUser *string            `json:"lastLoggedInUser,omitempty"`
	Contact          *ContactReference  `json:"contact,omitempty"`
	InstalledBy      *ContactReference  `json:"installedBy,omitempty"`
	Site             SiteReference      `json:"site"`
	Facility         *FacilityReference `json:"facility,omitempty"`
	Cabinet          *CabinetReference  `json:"cabinet,omitempty"`
	ReviewBy         *User              `json:"reviewBy,omitempty"`
	// Review Due date
	DueDate *string `json:"dueDate,omitempty"`
	// The JSON array designating the Services of the device.
	Services []Service `json:"services,omitempty"`
	// The JSON array designating the Network Interfaces.
	Ips []IP `json:"ips,omitempty"`
	// The default gateway of the device.
	DefaultGw  *string     `json:"defaultGw,omitempty"`
	Management *Management `json:"management,omitempty"`
	// Pop-up Notes  Yes/No.
	PopupNotes *bool `json:"popupNotes,omitempty"`
	// The JSON array designating the Device Notes.
	Notes []DeviceNote `json:"notes,omitempty"`
	// The foreign id of the synced integration.
	ForeignId *int64 `json:"foreignId,omitempty"`
	// The foreign type of the synced integration.
	ForeignType *string `json:"foreignType,omitempty"`
	// The link of the device.
	Url *string `json:"url,omitempty"`
	// in (true)/out of service (false)
	InOut *bool `json:"inOut,omitempty"`
	// Reason - why this item is being \"checked out/marked inactive\"
	InOutNotes *string `json:"inOutNotes,omitempty"`
	// The date the device was most recently modified.
	Modified             *string `json:"modified,omitempty"`
	Sheets               []Sheet `json:"sheets,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Device Device

// NewDevice instantiates a new Device object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDevice(company CompanyReference, name string, hostName string, type_ DeviceType, site SiteReference) *Device {
	this := Device{}
	this.Company = company
	this.Name = name
	this.HostName = hostName
	this.Type = type_
	this.Site = site
	return &this
}

// NewDeviceWithDefaults instantiates a new Device object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceWithDefaults() *Device {
	this := Device{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Device) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Device) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *Device) SetId(v int64) {
	o.Id = &v
}

// GetCompany returns the Company field value
func (o *Device) GetCompany() CompanyReference {
	if o == nil {
		var ret CompanyReference
		return ret
	}

	return o.Company
}

// GetCompanyOk returns a tuple with the Company field value
// and a boolean to check if the value has been set.
func (o *Device) GetCompanyOk() (*CompanyReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Company, true
}

// SetCompany sets field value
func (o *Device) SetCompany(v CompanyReference) {
	o.Company = v
}

// GetName returns the Name field value
func (o *Device) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Device) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Device) SetName(v string) {
	o.Name = v
}

// GetHostName returns the HostName field value
func (o *Device) GetHostName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HostName
}

// GetHostNameOk returns a tuple with the HostName field value
// and a boolean to check if the value has been set.
func (o *Device) GetHostNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostName, true
}

// SetHostName sets field value
func (o *Device) SetHostName(v string) {
	o.HostName = v
}

// GetType returns the Type field value
func (o *Device) GetType() DeviceType {
	if o == nil {
		var ret DeviceType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Device) GetTypeOk() (*DeviceType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Device) SetType(v DeviceType) {
	o.Type = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *Device) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *Device) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *Device) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *Device) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *Device) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *Device) SetPassword(v string) {
	o.Password = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Device) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Device) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Device) SetDescription(v string) {
	o.Description = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *Device) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *Device) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *Device) SetDomain(v string) {
	o.Domain = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *Device) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *Device) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *Device) SetLocation(v string) {
	o.Location = &v
}

// GetInstallDate returns the InstallDate field value if set, zero value otherwise.
func (o *Device) GetInstallDate() string {
	if o == nil || IsNil(o.InstallDate) {
		var ret string
		return ret
	}
	return *o.InstallDate
}

// GetInstallDateOk returns a tuple with the InstallDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetInstallDateOk() (*string, bool) {
	if o == nil || IsNil(o.InstallDate) {
		return nil, false
	}
	return o.InstallDate, true
}

// HasInstallDate returns a boolean if a field has been set.
func (o *Device) HasInstallDate() bool {
	if o != nil && !IsNil(o.InstallDate) {
		return true
	}

	return false
}

// SetInstallDate gets a reference to the given string and assigns it to the InstallDate field.
func (o *Device) SetInstallDate(v string) {
	o.InstallDate = &v
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise.
func (o *Device) GetManufacturer() string {
	if o == nil || IsNil(o.Manufacturer) {
		var ret string
		return ret
	}
	return *o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetManufacturerOk() (*string, bool) {
	if o == nil || IsNil(o.Manufacturer) {
		return nil, false
	}
	return o.Manufacturer, true
}

// HasManufacturer returns a boolean if a field has been set.
func (o *Device) HasManufacturer() bool {
	if o != nil && !IsNil(o.Manufacturer) {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given string and assigns it to the Manufacturer field.
func (o *Device) SetManufacturer(v string) {
	o.Manufacturer = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *Device) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *Device) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *Device) SetModel(v string) {
	o.Model = &v
}

// GetImei returns the Imei field value if set, zero value otherwise.
func (o *Device) GetImei() string {
	if o == nil || IsNil(o.Imei) {
		var ret string
		return ret
	}
	return *o.Imei
}

// GetImeiOk returns a tuple with the Imei field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetImeiOk() (*string, bool) {
	if o == nil || IsNil(o.Imei) {
		return nil, false
	}
	return o.Imei, true
}

// HasImei returns a boolean if a field has been set.
func (o *Device) HasImei() bool {
	if o != nil && !IsNil(o.Imei) {
		return true
	}

	return false
}

// SetImei gets a reference to the given string and assigns it to the Imei field.
func (o *Device) SetImei(v string) {
	o.Imei = &v
}

// GetSerial returns the Serial field value if set, zero value otherwise.
func (o *Device) GetSerial() string {
	if o == nil || IsNil(o.Serial) {
		var ret string
		return ret
	}
	return *o.Serial
}

// GetSerialOk returns a tuple with the Serial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetSerialOk() (*string, bool) {
	if o == nil || IsNil(o.Serial) {
		return nil, false
	}
	return o.Serial, true
}

// HasSerial returns a boolean if a field has been set.
func (o *Device) HasSerial() bool {
	if o != nil && !IsNil(o.Serial) {
		return true
	}

	return false
}

// SetSerial gets a reference to the given string and assigns it to the Serial field.
func (o *Device) SetSerial(v string) {
	o.Serial = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *Device) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *Device) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *Device) SetTag(v string) {
	o.Tag = &v
}

// GetPurchasePrice returns the PurchasePrice field value if set, zero value otherwise.
func (o *Device) GetPurchasePrice() float32 {
	if o == nil || IsNil(o.PurchasePrice) {
		var ret float32
		return ret
	}
	return *o.PurchasePrice
}

// GetPurchasePriceOk returns a tuple with the PurchasePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetPurchasePriceOk() (*float32, bool) {
	if o == nil || IsNil(o.PurchasePrice) {
		return nil, false
	}
	return o.PurchasePrice, true
}

// HasPurchasePrice returns a boolean if a field has been set.
func (o *Device) HasPurchasePrice() bool {
	if o != nil && !IsNil(o.PurchasePrice) {
		return true
	}

	return false
}

// SetPurchasePrice gets a reference to the given float32 and assigns it to the PurchasePrice field.
func (o *Device) SetPurchasePrice(v float32) {
	o.PurchasePrice = &v
}

// GetPurchaseDate returns the PurchaseDate field value if set, zero value otherwise.
func (o *Device) GetPurchaseDate() string {
	if o == nil || IsNil(o.PurchaseDate) {
		var ret string
		return ret
	}
	return *o.PurchaseDate
}

// GetPurchaseDateOk returns a tuple with the PurchaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetPurchaseDateOk() (*string, bool) {
	if o == nil || IsNil(o.PurchaseDate) {
		return nil, false
	}
	return o.PurchaseDate, true
}

// HasPurchaseDate returns a boolean if a field has been set.
func (o *Device) HasPurchaseDate() bool {
	if o != nil && !IsNil(o.PurchaseDate) {
		return true
	}

	return false
}

// SetPurchaseDate gets a reference to the given string and assigns it to the PurchaseDate field.
func (o *Device) SetPurchaseDate(v string) {
	o.PurchaseDate = &v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *Device) GetConfiguration() string {
	if o == nil || IsNil(o.Configuration) {
		var ret string
		return ret
	}
	return *o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetConfigurationOk() (*string, bool) {
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *Device) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given string and assigns it to the Configuration field.
func (o *Device) SetConfiguration(v string) {
	o.Configuration = &v
}

// GetWarrantyExpires returns the WarrantyExpires field value if set, zero value otherwise.
func (o *Device) GetWarrantyExpires() string {
	if o == nil || IsNil(o.WarrantyExpires) {
		var ret string
		return ret
	}
	return *o.WarrantyExpires
}

// GetWarrantyExpiresOk returns a tuple with the WarrantyExpires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetWarrantyExpiresOk() (*string, bool) {
	if o == nil || IsNil(o.WarrantyExpires) {
		return nil, false
	}
	return o.WarrantyExpires, true
}

// HasWarrantyExpires returns a boolean if a field has been set.
func (o *Device) HasWarrantyExpires() bool {
	if o != nil && !IsNil(o.WarrantyExpires) {
		return true
	}

	return false
}

// SetWarrantyExpires gets a reference to the given string and assigns it to the WarrantyExpires field.
func (o *Device) SetWarrantyExpires(v string) {
	o.WarrantyExpires = &v
}

// GetRetireDate returns the RetireDate field value if set, zero value otherwise.
func (o *Device) GetRetireDate() string {
	if o == nil || IsNil(o.RetireDate) {
		var ret string
		return ret
	}
	return *o.RetireDate
}

// GetRetireDateOk returns a tuple with the RetireDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetRetireDateOk() (*string, bool) {
	if o == nil || IsNil(o.RetireDate) {
		return nil, false
	}
	return o.RetireDate, true
}

// HasRetireDate returns a boolean if a field has been set.
func (o *Device) HasRetireDate() bool {
	if o != nil && !IsNil(o.RetireDate) {
		return true
	}

	return false
}

// SetRetireDate gets a reference to the given string and assigns it to the RetireDate field.
func (o *Device) SetRetireDate(v string) {
	o.RetireDate = &v
}

// GetLeaseEndDate returns the LeaseEndDate field value if set, zero value otherwise.
func (o *Device) GetLeaseEndDate() string {
	if o == nil || IsNil(o.LeaseEndDate) {
		var ret string
		return ret
	}
	return *o.LeaseEndDate
}

// GetLeaseEndDateOk returns a tuple with the LeaseEndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetLeaseEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.LeaseEndDate) {
		return nil, false
	}
	return o.LeaseEndDate, true
}

// HasLeaseEndDate returns a boolean if a field has been set.
func (o *Device) HasLeaseEndDate() bool {
	if o != nil && !IsNil(o.LeaseEndDate) {
		return true
	}

	return false
}

// SetLeaseEndDate gets a reference to the given string and assigns it to the LeaseEndDate field.
func (o *Device) SetLeaseEndDate(v string) {
	o.LeaseEndDate = &v
}

// GetLeased returns the Leased field value if set, zero value otherwise.
func (o *Device) GetLeased() bool {
	if o == nil || IsNil(o.Leased) {
		var ret bool
		return ret
	}
	return *o.Leased
}

// GetLeasedOk returns a tuple with the Leased field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetLeasedOk() (*bool, bool) {
	if o == nil || IsNil(o.Leased) {
		return nil, false
	}
	return o.Leased, true
}

// HasLeased returns a boolean if a field has been set.
func (o *Device) HasLeased() bool {
	if o != nil && !IsNil(o.Leased) {
		return true
	}

	return false
}

// SetLeased gets a reference to the given bool and assigns it to the Leased field.
func (o *Device) SetLeased(v bool) {
	o.Leased = &v
}

// GetOs returns the Os field value if set, zero value otherwise.
func (o *Device) GetOs() string {
	if o == nil || IsNil(o.Os) {
		var ret string
		return ret
	}
	return *o.Os
}

// GetOsOk returns a tuple with the Os field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetOsOk() (*string, bool) {
	if o == nil || IsNil(o.Os) {
		return nil, false
	}
	return o.Os, true
}

// HasOs returns a boolean if a field has been set.
func (o *Device) HasOs() bool {
	if o != nil && !IsNil(o.Os) {
		return true
	}

	return false
}

// SetOs gets a reference to the given string and assigns it to the Os field.
func (o *Device) SetOs(v string) {
	o.Os = &v
}

// GetBuildNumber returns the BuildNumber field value if set, zero value otherwise.
func (o *Device) GetBuildNumber() string {
	if o == nil || IsNil(o.BuildNumber) {
		var ret string
		return ret
	}
	return *o.BuildNumber
}

// GetBuildNumberOk returns a tuple with the BuildNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetBuildNumberOk() (*string, bool) {
	if o == nil || IsNil(o.BuildNumber) {
		return nil, false
	}
	return o.BuildNumber, true
}

// HasBuildNumber returns a boolean if a field has been set.
func (o *Device) HasBuildNumber() bool {
	if o != nil && !IsNil(o.BuildNumber) {
		return true
	}

	return false
}

// SetBuildNumber gets a reference to the given string and assigns it to the BuildNumber field.
func (o *Device) SetBuildNumber(v string) {
	o.BuildNumber = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *Device) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *Device) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *Device) SetVersion(v string) {
	o.Version = &v
}

// GetServicePack returns the ServicePack field value if set, zero value otherwise.
func (o *Device) GetServicePack() string {
	if o == nil || IsNil(o.ServicePack) {
		var ret string
		return ret
	}
	return *o.ServicePack
}

// GetServicePackOk returns a tuple with the ServicePack field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetServicePackOk() (*string, bool) {
	if o == nil || IsNil(o.ServicePack) {
		return nil, false
	}
	return o.ServicePack, true
}

// HasServicePack returns a boolean if a field has been set.
func (o *Device) HasServicePack() bool {
	if o != nil && !IsNil(o.ServicePack) {
		return true
	}

	return false
}

// SetServicePack gets a reference to the given string and assigns it to the ServicePack field.
func (o *Device) SetServicePack(v string) {
	o.ServicePack = &v
}

// GetCpu returns the Cpu field value if set, zero value otherwise.
func (o *Device) GetCpu() string {
	if o == nil || IsNil(o.Cpu) {
		var ret string
		return ret
	}
	return *o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetCpuOk() (*string, bool) {
	if o == nil || IsNil(o.Cpu) {
		return nil, false
	}
	return o.Cpu, true
}

// HasCpu returns a boolean if a field has been set.
func (o *Device) HasCpu() bool {
	if o != nil && !IsNil(o.Cpu) {
		return true
	}

	return false
}

// SetCpu gets a reference to the given string and assigns it to the Cpu field.
func (o *Device) SetCpu(v string) {
	o.Cpu = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *Device) GetMemory() int32 {
	if o == nil || IsNil(o.Memory) {
		var ret int32
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *Device) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given int32 and assigns it to the Memory field.
func (o *Device) SetMemory(v int32) {
	o.Memory = &v
}

// GetHardDiskInfo returns the HardDiskInfo field value if set, zero value otherwise.
func (o *Device) GetHardDiskInfo() string {
	if o == nil || IsNil(o.HardDiskInfo) {
		var ret string
		return ret
	}
	return *o.HardDiskInfo
}

// GetHardDiskInfoOk returns a tuple with the HardDiskInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetHardDiskInfoOk() (*string, bool) {
	if o == nil || IsNil(o.HardDiskInfo) {
		return nil, false
	}
	return o.HardDiskInfo, true
}

// HasHardDiskInfo returns a boolean if a field has been set.
func (o *Device) HasHardDiskInfo() bool {
	if o != nil && !IsNil(o.HardDiskInfo) {
		return true
	}

	return false
}

// SetHardDiskInfo gets a reference to the given string and assigns it to the HardDiskInfo field.
func (o *Device) SetHardDiskInfo(v string) {
	o.HardDiskInfo = &v
}

// GetRaidController returns the RaidController field value if set, zero value otherwise.
func (o *Device) GetRaidController() string {
	if o == nil || IsNil(o.RaidController) {
		var ret string
		return ret
	}
	return *o.RaidController
}

// GetRaidControllerOk returns a tuple with the RaidController field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetRaidControllerOk() (*string, bool) {
	if o == nil || IsNil(o.RaidController) {
		return nil, false
	}
	return o.RaidController, true
}

// HasRaidController returns a boolean if a field has been set.
func (o *Device) HasRaidController() bool {
	if o != nil && !IsNil(o.RaidController) {
		return true
	}

	return false
}

// SetRaidController gets a reference to the given string and assigns it to the RaidController field.
func (o *Device) SetRaidController(v string) {
	o.RaidController = &v
}

// GetScsiController returns the ScsiController field value if set, zero value otherwise.
func (o *Device) GetScsiController() string {
	if o == nil || IsNil(o.ScsiController) {
		var ret string
		return ret
	}
	return *o.ScsiController
}

// GetScsiControllerOk returns a tuple with the ScsiController field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetScsiControllerOk() (*string, bool) {
	if o == nil || IsNil(o.ScsiController) {
		return nil, false
	}
	return o.ScsiController, true
}

// HasScsiController returns a boolean if a field has been set.
func (o *Device) HasScsiController() bool {
	if o != nil && !IsNil(o.ScsiController) {
		return true
	}

	return false
}

// SetScsiController gets a reference to the given string and assigns it to the ScsiController field.
func (o *Device) SetScsiController(v string) {
	o.ScsiController = &v
}

// GetNumberCpu returns the NumberCpu field value if set, zero value otherwise.
func (o *Device) GetNumberCpu() int32 {
	if o == nil || IsNil(o.NumberCpu) {
		var ret int32
		return ret
	}
	return *o.NumberCpu
}

// GetNumberCpuOk returns a tuple with the NumberCpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetNumberCpuOk() (*int32, bool) {
	if o == nil || IsNil(o.NumberCpu) {
		return nil, false
	}
	return o.NumberCpu, true
}

// HasNumberCpu returns a boolean if a field has been set.
func (o *Device) HasNumberCpu() bool {
	if o != nil && !IsNil(o.NumberCpu) {
		return true
	}

	return false
}

// SetNumberCpu gets a reference to the given int32 and assigns it to the NumberCpu field.
func (o *Device) SetNumberCpu(v int32) {
	o.NumberCpu = &v
}

// GetProductKey returns the ProductKey field value if set, zero value otherwise.
func (o *Device) GetProductKey() string {
	if o == nil || IsNil(o.ProductKey) {
		var ret string
		return ret
	}
	return *o.ProductKey
}

// GetProductKeyOk returns a tuple with the ProductKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetProductKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ProductKey) {
		return nil, false
	}
	return o.ProductKey, true
}

// HasProductKey returns a boolean if a field has been set.
func (o *Device) HasProductKey() bool {
	if o != nil && !IsNil(o.ProductKey) {
		return true
	}

	return false
}

// SetProductKey gets a reference to the given string and assigns it to the ProductKey field.
func (o *Device) SetProductKey(v string) {
	o.ProductKey = &v
}

// GetLastLoggedInUser returns the LastLoggedInUser field value if set, zero value otherwise.
func (o *Device) GetLastLoggedInUser() string {
	if o == nil || IsNil(o.LastLoggedInUser) {
		var ret string
		return ret
	}
	return *o.LastLoggedInUser
}

// GetLastLoggedInUserOk returns a tuple with the LastLoggedInUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetLastLoggedInUserOk() (*string, bool) {
	if o == nil || IsNil(o.LastLoggedInUser) {
		return nil, false
	}
	return o.LastLoggedInUser, true
}

// HasLastLoggedInUser returns a boolean if a field has been set.
func (o *Device) HasLastLoggedInUser() bool {
	if o != nil && !IsNil(o.LastLoggedInUser) {
		return true
	}

	return false
}

// SetLastLoggedInUser gets a reference to the given string and assigns it to the LastLoggedInUser field.
func (o *Device) SetLastLoggedInUser(v string) {
	o.LastLoggedInUser = &v
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *Device) GetContact() ContactReference {
	if o == nil || IsNil(o.Contact) {
		var ret ContactReference
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetContactOk() (*ContactReference, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *Device) HasContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given ContactReference and assigns it to the Contact field.
func (o *Device) SetContact(v ContactReference) {
	o.Contact = &v
}

// GetInstalledBy returns the InstalledBy field value if set, zero value otherwise.
func (o *Device) GetInstalledBy() ContactReference {
	if o == nil || IsNil(o.InstalledBy) {
		var ret ContactReference
		return ret
	}
	return *o.InstalledBy
}

// GetInstalledByOk returns a tuple with the InstalledBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetInstalledByOk() (*ContactReference, bool) {
	if o == nil || IsNil(o.InstalledBy) {
		return nil, false
	}
	return o.InstalledBy, true
}

// HasInstalledBy returns a boolean if a field has been set.
func (o *Device) HasInstalledBy() bool {
	if o != nil && !IsNil(o.InstalledBy) {
		return true
	}

	return false
}

// SetInstalledBy gets a reference to the given ContactReference and assigns it to the InstalledBy field.
func (o *Device) SetInstalledBy(v ContactReference) {
	o.InstalledBy = &v
}

// GetSite returns the Site field value
func (o *Device) GetSite() SiteReference {
	if o == nil {
		var ret SiteReference
		return ret
	}

	return o.Site
}

// GetSiteOk returns a tuple with the Site field value
// and a boolean to check if the value has been set.
func (o *Device) GetSiteOk() (*SiteReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Site, true
}

// SetSite sets field value
func (o *Device) SetSite(v SiteReference) {
	o.Site = v
}

// GetFacility returns the Facility field value if set, zero value otherwise.
func (o *Device) GetFacility() FacilityReference {
	if o == nil || IsNil(o.Facility) {
		var ret FacilityReference
		return ret
	}
	return *o.Facility
}

// GetFacilityOk returns a tuple with the Facility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetFacilityOk() (*FacilityReference, bool) {
	if o == nil || IsNil(o.Facility) {
		return nil, false
	}
	return o.Facility, true
}

// HasFacility returns a boolean if a field has been set.
func (o *Device) HasFacility() bool {
	if o != nil && !IsNil(o.Facility) {
		return true
	}

	return false
}

// SetFacility gets a reference to the given FacilityReference and assigns it to the Facility field.
func (o *Device) SetFacility(v FacilityReference) {
	o.Facility = &v
}

// GetCabinet returns the Cabinet field value if set, zero value otherwise.
func (o *Device) GetCabinet() CabinetReference {
	if o == nil || IsNil(o.Cabinet) {
		var ret CabinetReference
		return ret
	}
	return *o.Cabinet
}

// GetCabinetOk returns a tuple with the Cabinet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetCabinetOk() (*CabinetReference, bool) {
	if o == nil || IsNil(o.Cabinet) {
		return nil, false
	}
	return o.Cabinet, true
}

// HasCabinet returns a boolean if a field has been set.
func (o *Device) HasCabinet() bool {
	if o != nil && !IsNil(o.Cabinet) {
		return true
	}

	return false
}

// SetCabinet gets a reference to the given CabinetReference and assigns it to the Cabinet field.
func (o *Device) SetCabinet(v CabinetReference) {
	o.Cabinet = &v
}

// GetReviewBy returns the ReviewBy field value if set, zero value otherwise.
func (o *Device) GetReviewBy() User {
	if o == nil || IsNil(o.ReviewBy) {
		var ret User
		return ret
	}
	return *o.ReviewBy
}

// GetReviewByOk returns a tuple with the ReviewBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetReviewByOk() (*User, bool) {
	if o == nil || IsNil(o.ReviewBy) {
		return nil, false
	}
	return o.ReviewBy, true
}

// HasReviewBy returns a boolean if a field has been set.
func (o *Device) HasReviewBy() bool {
	if o != nil && !IsNil(o.ReviewBy) {
		return true
	}

	return false
}

// SetReviewBy gets a reference to the given User and assigns it to the ReviewBy field.
func (o *Device) SetReviewBy(v User) {
	o.ReviewBy = &v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *Device) GetDueDate() string {
	if o == nil || IsNil(o.DueDate) {
		var ret string
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetDueDateOk() (*string, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *Device) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given string and assigns it to the DueDate field.
func (o *Device) SetDueDate(v string) {
	o.DueDate = &v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *Device) GetServices() []Service {
	if o == nil || IsNil(o.Services) {
		var ret []Service
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetServicesOk() ([]Service, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *Device) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []Service and assigns it to the Services field.
func (o *Device) SetServices(v []Service) {
	o.Services = v
}

// GetIps returns the Ips field value if set, zero value otherwise.
func (o *Device) GetIps() []IP {
	if o == nil || IsNil(o.Ips) {
		var ret []IP
		return ret
	}
	return o.Ips
}

// GetIpsOk returns a tuple with the Ips field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetIpsOk() ([]IP, bool) {
	if o == nil || IsNil(o.Ips) {
		return nil, false
	}
	return o.Ips, true
}

// HasIps returns a boolean if a field has been set.
func (o *Device) HasIps() bool {
	if o != nil && !IsNil(o.Ips) {
		return true
	}

	return false
}

// SetIps gets a reference to the given []IP and assigns it to the Ips field.
func (o *Device) SetIps(v []IP) {
	o.Ips = v
}

// GetDefaultGw returns the DefaultGw field value if set, zero value otherwise.
func (o *Device) GetDefaultGw() string {
	if o == nil || IsNil(o.DefaultGw) {
		var ret string
		return ret
	}
	return *o.DefaultGw
}

// GetDefaultGwOk returns a tuple with the DefaultGw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetDefaultGwOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultGw) {
		return nil, false
	}
	return o.DefaultGw, true
}

// HasDefaultGw returns a boolean if a field has been set.
func (o *Device) HasDefaultGw() bool {
	if o != nil && !IsNil(o.DefaultGw) {
		return true
	}

	return false
}

// SetDefaultGw gets a reference to the given string and assigns it to the DefaultGw field.
func (o *Device) SetDefaultGw(v string) {
	o.DefaultGw = &v
}

// GetManagement returns the Management field value if set, zero value otherwise.
func (o *Device) GetManagement() Management {
	if o == nil || IsNil(o.Management) {
		var ret Management
		return ret
	}
	return *o.Management
}

// GetManagementOk returns a tuple with the Management field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetManagementOk() (*Management, bool) {
	if o == nil || IsNil(o.Management) {
		return nil, false
	}
	return o.Management, true
}

// HasManagement returns a boolean if a field has been set.
func (o *Device) HasManagement() bool {
	if o != nil && !IsNil(o.Management) {
		return true
	}

	return false
}

// SetManagement gets a reference to the given Management and assigns it to the Management field.
func (o *Device) SetManagement(v Management) {
	o.Management = &v
}

// GetPopupNotes returns the PopupNotes field value if set, zero value otherwise.
func (o *Device) GetPopupNotes() bool {
	if o == nil || IsNil(o.PopupNotes) {
		var ret bool
		return ret
	}
	return *o.PopupNotes
}

// GetPopupNotesOk returns a tuple with the PopupNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetPopupNotesOk() (*bool, bool) {
	if o == nil || IsNil(o.PopupNotes) {
		return nil, false
	}
	return o.PopupNotes, true
}

// HasPopupNotes returns a boolean if a field has been set.
func (o *Device) HasPopupNotes() bool {
	if o != nil && !IsNil(o.PopupNotes) {
		return true
	}

	return false
}

// SetPopupNotes gets a reference to the given bool and assigns it to the PopupNotes field.
func (o *Device) SetPopupNotes(v bool) {
	o.PopupNotes = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *Device) GetNotes() []DeviceNote {
	if o == nil || IsNil(o.Notes) {
		var ret []DeviceNote
		return ret
	}
	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetNotesOk() ([]DeviceNote, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *Device) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []DeviceNote and assigns it to the Notes field.
func (o *Device) SetNotes(v []DeviceNote) {
	o.Notes = v
}

// GetForeignId returns the ForeignId field value if set, zero value otherwise.
func (o *Device) GetForeignId() int64 {
	if o == nil || IsNil(o.ForeignId) {
		var ret int64
		return ret
	}
	return *o.ForeignId
}

// GetForeignIdOk returns a tuple with the ForeignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetForeignIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ForeignId) {
		return nil, false
	}
	return o.ForeignId, true
}

// HasForeignId returns a boolean if a field has been set.
func (o *Device) HasForeignId() bool {
	if o != nil && !IsNil(o.ForeignId) {
		return true
	}

	return false
}

// SetForeignId gets a reference to the given int64 and assigns it to the ForeignId field.
func (o *Device) SetForeignId(v int64) {
	o.ForeignId = &v
}

// GetForeignType returns the ForeignType field value if set, zero value otherwise.
func (o *Device) GetForeignType() string {
	if o == nil || IsNil(o.ForeignType) {
		var ret string
		return ret
	}
	return *o.ForeignType
}

// GetForeignTypeOk returns a tuple with the ForeignType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetForeignTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ForeignType) {
		return nil, false
	}
	return o.ForeignType, true
}

// HasForeignType returns a boolean if a field has been set.
func (o *Device) HasForeignType() bool {
	if o != nil && !IsNil(o.ForeignType) {
		return true
	}

	return false
}

// SetForeignType gets a reference to the given string and assigns it to the ForeignType field.
func (o *Device) SetForeignType(v string) {
	o.ForeignType = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Device) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Device) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Device) SetUrl(v string) {
	o.Url = &v
}

// GetInOut returns the InOut field value if set, zero value otherwise.
func (o *Device) GetInOut() bool {
	if o == nil || IsNil(o.InOut) {
		var ret bool
		return ret
	}
	return *o.InOut
}

// GetInOutOk returns a tuple with the InOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetInOutOk() (*bool, bool) {
	if o == nil || IsNil(o.InOut) {
		return nil, false
	}
	return o.InOut, true
}

// HasInOut returns a boolean if a field has been set.
func (o *Device) HasInOut() bool {
	if o != nil && !IsNil(o.InOut) {
		return true
	}

	return false
}

// SetInOut gets a reference to the given bool and assigns it to the InOut field.
func (o *Device) SetInOut(v bool) {
	o.InOut = &v
}

// GetInOutNotes returns the InOutNotes field value if set, zero value otherwise.
func (o *Device) GetInOutNotes() string {
	if o == nil || IsNil(o.InOutNotes) {
		var ret string
		return ret
	}
	return *o.InOutNotes
}

// GetInOutNotesOk returns a tuple with the InOutNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetInOutNotesOk() (*string, bool) {
	if o == nil || IsNil(o.InOutNotes) {
		return nil, false
	}
	return o.InOutNotes, true
}

// HasInOutNotes returns a boolean if a field has been set.
func (o *Device) HasInOutNotes() bool {
	if o != nil && !IsNil(o.InOutNotes) {
		return true
	}

	return false
}

// SetInOutNotes gets a reference to the given string and assigns it to the InOutNotes field.
func (o *Device) SetInOutNotes(v string) {
	o.InOutNotes = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *Device) GetModified() string {
	if o == nil || IsNil(o.Modified) {
		var ret string
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetModifiedOk() (*string, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *Device) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given string and assigns it to the Modified field.
func (o *Device) SetModified(v string) {
	o.Modified = &v
}

// GetSheets returns the Sheets field value if set, zero value otherwise.
func (o *Device) GetSheets() []Sheet {
	if o == nil || IsNil(o.Sheets) {
		var ret []Sheet
		return ret
	}
	return o.Sheets
}

// GetSheetsOk returns a tuple with the Sheets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Device) GetSheetsOk() ([]Sheet, bool) {
	if o == nil || IsNil(o.Sheets) {
		return nil, false
	}
	return o.Sheets, true
}

// HasSheets returns a boolean if a field has been set.
func (o *Device) HasSheets() bool {
	if o != nil && !IsNil(o.Sheets) {
		return true
	}

	return false
}

// SetSheets gets a reference to the given []Sheet and assigns it to the Sheets field.
func (o *Device) SetSheets(v []Sheet) {
	o.Sheets = v
}

func (o Device) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Device) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["company"] = o.Company
	toSerialize["name"] = o.Name
	toSerialize["hostName"] = o.HostName
	toSerialize["type"] = o.Type
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.InstallDate) {
		toSerialize["installDate"] = o.InstallDate
	}
	if !IsNil(o.Manufacturer) {
		toSerialize["manufacturer"] = o.Manufacturer
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Imei) {
		toSerialize["imei"] = o.Imei
	}
	if !IsNil(o.Serial) {
		toSerialize["serial"] = o.Serial
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.PurchasePrice) {
		toSerialize["purchasePrice"] = o.PurchasePrice
	}
	if !IsNil(o.PurchaseDate) {
		toSerialize["purchaseDate"] = o.PurchaseDate
	}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	if !IsNil(o.WarrantyExpires) {
		toSerialize["warrantyExpires"] = o.WarrantyExpires
	}
	if !IsNil(o.RetireDate) {
		toSerialize["retireDate"] = o.RetireDate
	}
	if !IsNil(o.LeaseEndDate) {
		toSerialize["leaseEndDate"] = o.LeaseEndDate
	}
	if !IsNil(o.Leased) {
		toSerialize["leased"] = o.Leased
	}
	if !IsNil(o.Os) {
		toSerialize["os"] = o.Os
	}
	if !IsNil(o.BuildNumber) {
		toSerialize["buildNumber"] = o.BuildNumber
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.ServicePack) {
		toSerialize["servicePack"] = o.ServicePack
	}
	if !IsNil(o.Cpu) {
		toSerialize["cpu"] = o.Cpu
	}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.HardDiskInfo) {
		toSerialize["hardDiskInfo"] = o.HardDiskInfo
	}
	if !IsNil(o.RaidController) {
		toSerialize["raidController"] = o.RaidController
	}
	if !IsNil(o.ScsiController) {
		toSerialize["scsiController"] = o.ScsiController
	}
	if !IsNil(o.NumberCpu) {
		toSerialize["numberCpu"] = o.NumberCpu
	}
	if !IsNil(o.ProductKey) {
		toSerialize["productKey"] = o.ProductKey
	}
	if !IsNil(o.LastLoggedInUser) {
		toSerialize["lastLoggedInUser"] = o.LastLoggedInUser
	}
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	if !IsNil(o.InstalledBy) {
		toSerialize["installedBy"] = o.InstalledBy
	}
	toSerialize["site"] = o.Site
	if !IsNil(o.Facility) {
		toSerialize["facility"] = o.Facility
	}
	if !IsNil(o.Cabinet) {
		toSerialize["cabinet"] = o.Cabinet
	}
	if !IsNil(o.ReviewBy) {
		toSerialize["reviewBy"] = o.ReviewBy
	}
	if !IsNil(o.DueDate) {
		toSerialize["dueDate"] = o.DueDate
	}
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	if !IsNil(o.Ips) {
		toSerialize["ips"] = o.Ips
	}
	if !IsNil(o.DefaultGw) {
		toSerialize["defaultGw"] = o.DefaultGw
	}
	if !IsNil(o.Management) {
		toSerialize["management"] = o.Management
	}
	if !IsNil(o.PopupNotes) {
		toSerialize["popupNotes"] = o.PopupNotes
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.ForeignId) {
		toSerialize["foreignId"] = o.ForeignId
	}
	if !IsNil(o.ForeignType) {
		toSerialize["foreignType"] = o.ForeignType
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.InOut) {
		toSerialize["inOut"] = o.InOut
	}
	if !IsNil(o.InOutNotes) {
		toSerialize["inOutNotes"] = o.InOutNotes
	}
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	if !IsNil(o.Sheets) {
		toSerialize["sheets"] = o.Sheets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Device) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"company",
		"name",
		"hostName",
		"type",
		"site",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDevice := _Device{}

	err = json.Unmarshal(data, &varDevice)

	if err != nil {
		return err
	}

	*o = Device(varDevice)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "company")
		delete(additionalProperties, "name")
		delete(additionalProperties, "hostName")
		delete(additionalProperties, "type")
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		delete(additionalProperties, "description")
		delete(additionalProperties, "domain")
		delete(additionalProperties, "location")
		delete(additionalProperties, "installDate")
		delete(additionalProperties, "manufacturer")
		delete(additionalProperties, "model")
		delete(additionalProperties, "imei")
		delete(additionalProperties, "serial")
		delete(additionalProperties, "tag")
		delete(additionalProperties, "purchasePrice")
		delete(additionalProperties, "purchaseDate")
		delete(additionalProperties, "configuration")
		delete(additionalProperties, "warrantyExpires")
		delete(additionalProperties, "retireDate")
		delete(additionalProperties, "leaseEndDate")
		delete(additionalProperties, "leased")
		delete(additionalProperties, "os")
		delete(additionalProperties, "buildNumber")
		delete(additionalProperties, "version")
		delete(additionalProperties, "servicePack")
		delete(additionalProperties, "cpu")
		delete(additionalProperties, "memory")
		delete(additionalProperties, "hardDiskInfo")
		delete(additionalProperties, "raidController")
		delete(additionalProperties, "scsiController")
		delete(additionalProperties, "numberCpu")
		delete(additionalProperties, "productKey")
		delete(additionalProperties, "lastLoggedInUser")
		delete(additionalProperties, "contact")
		delete(additionalProperties, "installedBy")
		delete(additionalProperties, "site")
		delete(additionalProperties, "facility")
		delete(additionalProperties, "cabinet")
		delete(additionalProperties, "reviewBy")
		delete(additionalProperties, "dueDate")
		delete(additionalProperties, "services")
		delete(additionalProperties, "ips")
		delete(additionalProperties, "defaultGw")
		delete(additionalProperties, "management")
		delete(additionalProperties, "popupNotes")
		delete(additionalProperties, "notes")
		delete(additionalProperties, "foreignId")
		delete(additionalProperties, "foreignType")
		delete(additionalProperties, "url")
		delete(additionalProperties, "inOut")
		delete(additionalProperties, "inOutNotes")
		delete(additionalProperties, "modified")
		delete(additionalProperties, "sheets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDevice struct {
	value *Device
	isSet bool
}

func (v NullableDevice) Get() *Device {
	return v.value
}

func (v *NullableDevice) Set(val *Device) {
	v.value = val
	v.isSet = true
}

func (v NullableDevice) IsSet() bool {
	return v.isSet
}

func (v *NullableDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDevice(val *Device) *NullableDevice {
	return &NullableDevice{value: val, isSet: true}
}

func (v NullableDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
