/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the DocumentReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentReference{}

// DocumentReference struct for DocumentReference
type DocumentReference struct {
	// The unique ID of the document.
	Id *int64 `json:"id,omitempty"`
	// The name of the document.
	Name                 *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DocumentReference DocumentReference

// NewDocumentReference instantiates a new DocumentReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentReference() *DocumentReference {
	this := DocumentReference{}
	return &this
}

// NewDocumentReferenceWithDefaults instantiates a new DocumentReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentReferenceWithDefaults() *DocumentReference {
	this := DocumentReference{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DocumentReference) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentReference) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DocumentReference) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *DocumentReference) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DocumentReference) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentReference) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DocumentReference) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DocumentReference) SetName(v string) {
	o.Name = &v
}

func (o DocumentReference) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DocumentReference) UnmarshalJSON(data []byte) (err error) {
	varDocumentReference := _DocumentReference{}

	err = json.Unmarshal(data, &varDocumentReference)

	if err != nil {
		return err
	}

	*o = DocumentReference(varDocumentReference)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDocumentReference struct {
	value *DocumentReference
	isSet bool
}

func (v NullableDocumentReference) Get() *DocumentReference {
	return v.value
}

func (v *NullableDocumentReference) Set(val *DocumentReference) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentReference) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentReference(val *DocumentReference) *NullableDocumentReference {
	return &NullableDocumentReference{value: val, isSet: true}
}

func (v NullableDocumentReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
