/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the TemplateDataWrapper type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateDataWrapper{}

// TemplateDataWrapper struct for TemplateDataWrapper
type TemplateDataWrapper struct {
	// The HTTP status code of the returned result.
	Code *int32 `json:"code,omitempty"`
	// A string description of the call status.
	Status *string                `json:"status,omitempty"`
	Data   *TemplateDataContainer `json:"data,omitempty"`
	// A digest value of the content returned by the call.
	Etag                 *string `json:"etag,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TemplateDataWrapper TemplateDataWrapper

// NewTemplateDataWrapper instantiates a new TemplateDataWrapper object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateDataWrapper() *TemplateDataWrapper {
	this := TemplateDataWrapper{}
	return &this
}

// NewTemplateDataWrapperWithDefaults instantiates a new TemplateDataWrapper object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateDataWrapperWithDefaults() *TemplateDataWrapper {
	this := TemplateDataWrapper{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *TemplateDataWrapper) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateDataWrapper) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *TemplateDataWrapper) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *TemplateDataWrapper) SetCode(v int32) {
	o.Code = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TemplateDataWrapper) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateDataWrapper) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TemplateDataWrapper) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TemplateDataWrapper) SetStatus(v string) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TemplateDataWrapper) GetData() TemplateDataContainer {
	if o == nil || IsNil(o.Data) {
		var ret TemplateDataContainer
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateDataWrapper) GetDataOk() (*TemplateDataContainer, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TemplateDataWrapper) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given TemplateDataContainer and assigns it to the Data field.
func (o *TemplateDataWrapper) SetData(v TemplateDataContainer) {
	o.Data = &v
}

// GetEtag returns the Etag field value if set, zero value otherwise.
func (o *TemplateDataWrapper) GetEtag() string {
	if o == nil || IsNil(o.Etag) {
		var ret string
		return ret
	}
	return *o.Etag
}

// GetEtagOk returns a tuple with the Etag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateDataWrapper) GetEtagOk() (*string, bool) {
	if o == nil || IsNil(o.Etag) {
		return nil, false
	}
	return o.Etag, true
}

// HasEtag returns a boolean if a field has been set.
func (o *TemplateDataWrapper) HasEtag() bool {
	if o != nil && !IsNil(o.Etag) {
		return true
	}

	return false
}

// SetEtag gets a reference to the given string and assigns it to the Etag field.
func (o *TemplateDataWrapper) SetEtag(v string) {
	o.Etag = &v
}

func (o TemplateDataWrapper) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateDataWrapper) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Etag) {
		toSerialize["etag"] = o.Etag
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TemplateDataWrapper) UnmarshalJSON(data []byte) (err error) {
	varTemplateDataWrapper := _TemplateDataWrapper{}

	err = json.Unmarshal(data, &varTemplateDataWrapper)

	if err != nil {
		return err
	}

	*o = TemplateDataWrapper(varTemplateDataWrapper)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "status")
		delete(additionalProperties, "data")
		delete(additionalProperties, "etag")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTemplateDataWrapper struct {
	value *TemplateDataWrapper
	isSet bool
}

func (v NullableTemplateDataWrapper) Get() *TemplateDataWrapper {
	return v.value
}

func (v *NullableTemplateDataWrapper) Set(val *TemplateDataWrapper) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateDataWrapper) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateDataWrapper) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateDataWrapper(val *TemplateDataWrapper) *NullableTemplateDataWrapper {
	return &NullableTemplateDataWrapper{value: val, isSet: true}
}

func (v NullableTemplateDataWrapper) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateDataWrapper) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
