/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the FieldValueDataContainer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FieldValueDataContainer{}

// FieldValueDataContainer struct for FieldValueDataContainer
type FieldValueDataContainer struct {
	// The requested offset (number of skipped results) of the call.
	Offset *int32 `json:"offset,omitempty"`
	// The requested result limit.
	Limit *int32 `json:"limit,omitempty"`
	// The total number of resources available given the current filter set.
	Total *int64 `json:"total,omitempty"`
	// The total number of results returned by this call.
	Count *int64 `json:"count,omitempty"`
	// The list of field values returned by the call.
	Results              []ObjectWithTemplate `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FieldValueDataContainer FieldValueDataContainer

// NewFieldValueDataContainer instantiates a new FieldValueDataContainer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldValueDataContainer() *FieldValueDataContainer {
	this := FieldValueDataContainer{}
	return &this
}

// NewFieldValueDataContainerWithDefaults instantiates a new FieldValueDataContainer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldValueDataContainerWithDefaults() *FieldValueDataContainer {
	this := FieldValueDataContainer{}
	return &this
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *FieldValueDataContainer) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldValueDataContainer) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *FieldValueDataContainer) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *FieldValueDataContainer) SetOffset(v int32) {
	o.Offset = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *FieldValueDataContainer) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldValueDataContainer) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *FieldValueDataContainer) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *FieldValueDataContainer) SetLimit(v int32) {
	o.Limit = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *FieldValueDataContainer) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldValueDataContainer) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *FieldValueDataContainer) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *FieldValueDataContainer) SetTotal(v int64) {
	o.Total = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *FieldValueDataContainer) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldValueDataContainer) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *FieldValueDataContainer) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *FieldValueDataContainer) SetCount(v int64) {
	o.Count = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *FieldValueDataContainer) GetResults() []ObjectWithTemplate {
	if o == nil || IsNil(o.Results) {
		var ret []ObjectWithTemplate
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldValueDataContainer) GetResultsOk() ([]ObjectWithTemplate, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *FieldValueDataContainer) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []ObjectWithTemplate and assigns it to the Results field.
func (o *FieldValueDataContainer) SetResults(v []ObjectWithTemplate) {
	o.Results = v
}

func (o FieldValueDataContainer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FieldValueDataContainer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FieldValueDataContainer) UnmarshalJSON(data []byte) (err error) {
	varFieldValueDataContainer := _FieldValueDataContainer{}

	err = json.Unmarshal(data, &varFieldValueDataContainer)

	if err != nil {
		return err
	}

	*o = FieldValueDataContainer(varFieldValueDataContainer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "offset")
		delete(additionalProperties, "limit")
		delete(additionalProperties, "total")
		delete(additionalProperties, "count")
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFieldValueDataContainer struct {
	value *FieldValueDataContainer
	isSet bool
}

func (v NullableFieldValueDataContainer) Get() *FieldValueDataContainer {
	return v.value
}

func (v *NullableFieldValueDataContainer) Set(val *FieldValueDataContainer) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldValueDataContainer) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldValueDataContainer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldValueDataContainer(val *FieldValueDataContainer) *NullableFieldValueDataContainer {
	return &NullableFieldValueDataContainer{value: val, isSet: true}
}

func (v NullableFieldValueDataContainer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldValueDataContainer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
