/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the TemplateField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateField{}

// TemplateField struct for TemplateField
type TemplateField struct {
	// The unique ID of the template field.
	Id *int64 `json:"id,omitempty"`
	// The name of the template field.
	Name      *string `json:"name,omitempty"`
	FieldType *string `json:"fieldType,omitempty"`
	// A description of the template field.
	Description *string `json:"description,omitempty"`
	// An icon of the template field.
	Icon *string `json:"icon,omitempty"`
	// Requires data entry
	IsRequired *bool `json:"isRequired,omitempty"`
	// Any valid value
	FieldValue           interface{} `json:"fieldValue,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TemplateField TemplateField

// NewTemplateField instantiates a new TemplateField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateField() *TemplateField {
	this := TemplateField{}
	return &this
}

// NewTemplateFieldWithDefaults instantiates a new TemplateField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateFieldWithDefaults() *TemplateField {
	this := TemplateField{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TemplateField) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateField) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TemplateField) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *TemplateField) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TemplateField) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateField) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TemplateField) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TemplateField) SetName(v string) {
	o.Name = &v
}

// GetFieldType returns the FieldType field value if set, zero value otherwise.
func (o *TemplateField) GetFieldType() string {
	if o == nil || IsNil(o.FieldType) {
		var ret string
		return ret
	}
	return *o.FieldType
}

// GetFieldTypeOk returns a tuple with the FieldType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateField) GetFieldTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FieldType) {
		return nil, false
	}
	return o.FieldType, true
}

// HasFieldType returns a boolean if a field has been set.
func (o *TemplateField) HasFieldType() bool {
	if o != nil && !IsNil(o.FieldType) {
		return true
	}

	return false
}

// SetFieldType gets a reference to the given string and assigns it to the FieldType field.
func (o *TemplateField) SetFieldType(v string) {
	o.FieldType = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TemplateField) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateField) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TemplateField) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TemplateField) SetDescription(v string) {
	o.Description = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *TemplateField) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateField) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *TemplateField) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *TemplateField) SetIcon(v string) {
	o.Icon = &v
}

// GetIsRequired returns the IsRequired field value if set, zero value otherwise.
func (o *TemplateField) GetIsRequired() bool {
	if o == nil || IsNil(o.IsRequired) {
		var ret bool
		return ret
	}
	return *o.IsRequired
}

// GetIsRequiredOk returns a tuple with the IsRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateField) GetIsRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.IsRequired) {
		return nil, false
	}
	return o.IsRequired, true
}

// HasIsRequired returns a boolean if a field has been set.
func (o *TemplateField) HasIsRequired() bool {
	if o != nil && !IsNil(o.IsRequired) {
		return true
	}

	return false
}

// SetIsRequired gets a reference to the given bool and assigns it to the IsRequired field.
func (o *TemplateField) SetIsRequired(v bool) {
	o.IsRequired = &v
}

// GetFieldValue returns the FieldValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateField) GetFieldValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.FieldValue
}

// GetFieldValueOk returns a tuple with the FieldValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateField) GetFieldValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.FieldValue) {
		return nil, false
	}
	return &o.FieldValue, true
}

// HasFieldValue returns a boolean if a field has been set.
func (o *TemplateField) HasFieldValue() bool {
	if o != nil && !IsNil(o.FieldValue) {
		return true
	}

	return false
}

// SetFieldValue gets a reference to the given interface{} and assigns it to the FieldValue field.
func (o *TemplateField) SetFieldValue(v interface{}) {
	o.FieldValue = v
}

func (o TemplateField) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.FieldType) {
		toSerialize["fieldType"] = o.FieldType
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.IsRequired) {
		toSerialize["isRequired"] = o.IsRequired
	}
	if o.FieldValue != nil {
		toSerialize["fieldValue"] = o.FieldValue
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TemplateField) UnmarshalJSON(data []byte) (err error) {
	varTemplateField := _TemplateField{}

	err = json.Unmarshal(data, &varTemplateField)

	if err != nil {
		return err
	}

	*o = TemplateField(varTemplateField)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "fieldType")
		delete(additionalProperties, "description")
		delete(additionalProperties, "icon")
		delete(additionalProperties, "isRequired")
		delete(additionalProperties, "fieldValue")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTemplateField struct {
	value *TemplateField
	isSet bool
}

func (v NullableTemplateField) Get() *TemplateField {
	return v.value
}

func (v *NullableTemplateField) Set(val *TemplateField) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateField) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateField(val *TemplateField) *NullableTemplateField {
	return &NullableTemplateField{value: val, isSet: true}
}

func (v NullableTemplateField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
