/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the IPNetwork type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPNetwork{}

// IPNetwork struct for IPNetwork
type IPNetwork struct {
	// The unique ID of the IP Network.
	Id      *int64           `json:"id,omitempty"`
	Company CompanyReference `json:"company"`
	// Network Name
	Name string `json:"name"`
	// The notes of the IP Network.
	Notes *string `json:"notes,omitempty"`
	// Description
	Description *string       `json:"description,omitempty"`
	Site        SiteReference `json:"site"`
	// Network Address
	NetworkAddress string       `json:"networkAddress"`
	DnsServer1     *IPReference `json:"dnsServer1,omitempty"`
	DnsServer2     *IPReference `json:"dnsServer2,omitempty"`
	DhcpServer     *IPReference `json:"dhcpServer,omitempty"`
	DefaultGateway *IPReference `json:"defaultGateway,omitempty"`
	// Subnet Mask
	SubnetMask string `json:"subnetMask"`
	// Subnet Mask IP Version
	IpVersion *string `json:"ipVersion,omitempty"`
	// VLAN ID
	VlanId   *int32 `json:"vlanId,omitempty"`
	ReviewBy *User  `json:"reviewBy,omitempty"`
	// Review Due date
	DueDate *string `json:"dueDate,omitempty"`
	// The link of the IP Network.
	Url *string `json:"url,omitempty"`
	// The date the IP Network was most recently modified.
	Modified             *time.Time `json:"modified,omitempty"`
	Sheets               *Sheet     `json:"sheets,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IPNetwork IPNetwork

// NewIPNetwork instantiates a new IPNetwork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPNetwork(company CompanyReference, name string, site SiteReference, networkAddress string, subnetMask string) *IPNetwork {
	this := IPNetwork{}
	this.Company = company
	this.Name = name
	this.Site = site
	this.NetworkAddress = networkAddress
	this.SubnetMask = subnetMask
	return &this
}

// NewIPNetworkWithDefaults instantiates a new IPNetwork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPNetworkWithDefaults() *IPNetwork {
	this := IPNetwork{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IPNetwork) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IPNetwork) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *IPNetwork) SetId(v int64) {
	o.Id = &v
}

// GetCompany returns the Company field value
func (o *IPNetwork) GetCompany() CompanyReference {
	if o == nil {
		var ret CompanyReference
		return ret
	}

	return o.Company
}

// GetCompanyOk returns a tuple with the Company field value
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetCompanyOk() (*CompanyReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Company, true
}

// SetCompany sets field value
func (o *IPNetwork) SetCompany(v CompanyReference) {
	o.Company = v
}

// GetName returns the Name field value
func (o *IPNetwork) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IPNetwork) SetName(v string) {
	o.Name = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *IPNetwork) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *IPNetwork) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *IPNetwork) SetNotes(v string) {
	o.Notes = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *IPNetwork) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *IPNetwork) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *IPNetwork) SetDescription(v string) {
	o.Description = &v
}

// GetSite returns the Site field value
func (o *IPNetwork) GetSite() SiteReference {
	if o == nil {
		var ret SiteReference
		return ret
	}

	return o.Site
}

// GetSiteOk returns a tuple with the Site field value
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetSiteOk() (*SiteReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Site, true
}

// SetSite sets field value
func (o *IPNetwork) SetSite(v SiteReference) {
	o.Site = v
}

// GetNetworkAddress returns the NetworkAddress field value
func (o *IPNetwork) GetNetworkAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetworkAddress
}

// GetNetworkAddressOk returns a tuple with the NetworkAddress field value
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetNetworkAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkAddress, true
}

// SetNetworkAddress sets field value
func (o *IPNetwork) SetNetworkAddress(v string) {
	o.NetworkAddress = v
}

// GetDnsServer1 returns the DnsServer1 field value if set, zero value otherwise.
func (o *IPNetwork) GetDnsServer1() IPReference {
	if o == nil || IsNil(o.DnsServer1) {
		var ret IPReference
		return ret
	}
	return *o.DnsServer1
}

// GetDnsServer1Ok returns a tuple with the DnsServer1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetDnsServer1Ok() (*IPReference, bool) {
	if o == nil || IsNil(o.DnsServer1) {
		return nil, false
	}
	return o.DnsServer1, true
}

// HasDnsServer1 returns a boolean if a field has been set.
func (o *IPNetwork) HasDnsServer1() bool {
	if o != nil && !IsNil(o.DnsServer1) {
		return true
	}

	return false
}

// SetDnsServer1 gets a reference to the given IPReference and assigns it to the DnsServer1 field.
func (o *IPNetwork) SetDnsServer1(v IPReference) {
	o.DnsServer1 = &v
}

// GetDnsServer2 returns the DnsServer2 field value if set, zero value otherwise.
func (o *IPNetwork) GetDnsServer2() IPReference {
	if o == nil || IsNil(o.DnsServer2) {
		var ret IPReference
		return ret
	}
	return *o.DnsServer2
}

// GetDnsServer2Ok returns a tuple with the DnsServer2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetDnsServer2Ok() (*IPReference, bool) {
	if o == nil || IsNil(o.DnsServer2) {
		return nil, false
	}
	return o.DnsServer2, true
}

// HasDnsServer2 returns a boolean if a field has been set.
func (o *IPNetwork) HasDnsServer2() bool {
	if o != nil && !IsNil(o.DnsServer2) {
		return true
	}

	return false
}

// SetDnsServer2 gets a reference to the given IPReference and assigns it to the DnsServer2 field.
func (o *IPNetwork) SetDnsServer2(v IPReference) {
	o.DnsServer2 = &v
}

// GetDhcpServer returns the DhcpServer field value if set, zero value otherwise.
func (o *IPNetwork) GetDhcpServer() IPReference {
	if o == nil || IsNil(o.DhcpServer) {
		var ret IPReference
		return ret
	}
	return *o.DhcpServer
}

// GetDhcpServerOk returns a tuple with the DhcpServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetDhcpServerOk() (*IPReference, bool) {
	if o == nil || IsNil(o.DhcpServer) {
		return nil, false
	}
	return o.DhcpServer, true
}

// HasDhcpServer returns a boolean if a field has been set.
func (o *IPNetwork) HasDhcpServer() bool {
	if o != nil && !IsNil(o.DhcpServer) {
		return true
	}

	return false
}

// SetDhcpServer gets a reference to the given IPReference and assigns it to the DhcpServer field.
func (o *IPNetwork) SetDhcpServer(v IPReference) {
	o.DhcpServer = &v
}

// GetDefaultGateway returns the DefaultGateway field value if set, zero value otherwise.
func (o *IPNetwork) GetDefaultGateway() IPReference {
	if o == nil || IsNil(o.DefaultGateway) {
		var ret IPReference
		return ret
	}
	return *o.DefaultGateway
}

// GetDefaultGatewayOk returns a tuple with the DefaultGateway field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetDefaultGatewayOk() (*IPReference, bool) {
	if o == nil || IsNil(o.DefaultGateway) {
		return nil, false
	}
	return o.DefaultGateway, true
}

// HasDefaultGateway returns a boolean if a field has been set.
func (o *IPNetwork) HasDefaultGateway() bool {
	if o != nil && !IsNil(o.DefaultGateway) {
		return true
	}

	return false
}

// SetDefaultGateway gets a reference to the given IPReference and assigns it to the DefaultGateway field.
func (o *IPNetwork) SetDefaultGateway(v IPReference) {
	o.DefaultGateway = &v
}

// GetSubnetMask returns the SubnetMask field value
func (o *IPNetwork) GetSubnetMask() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubnetMask
}

// GetSubnetMaskOk returns a tuple with the SubnetMask field value
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetSubnetMaskOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubnetMask, true
}

// SetSubnetMask sets field value
func (o *IPNetwork) SetSubnetMask(v string) {
	o.SubnetMask = v
}

// GetIpVersion returns the IpVersion field value if set, zero value otherwise.
func (o *IPNetwork) GetIpVersion() string {
	if o == nil || IsNil(o.IpVersion) {
		var ret string
		return ret
	}
	return *o.IpVersion
}

// GetIpVersionOk returns a tuple with the IpVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetIpVersionOk() (*string, bool) {
	if o == nil || IsNil(o.IpVersion) {
		return nil, false
	}
	return o.IpVersion, true
}

// HasIpVersion returns a boolean if a field has been set.
func (o *IPNetwork) HasIpVersion() bool {
	if o != nil && !IsNil(o.IpVersion) {
		return true
	}

	return false
}

// SetIpVersion gets a reference to the given string and assigns it to the IpVersion field.
func (o *IPNetwork) SetIpVersion(v string) {
	o.IpVersion = &v
}

// GetVlanId returns the VlanId field value if set, zero value otherwise.
func (o *IPNetwork) GetVlanId() int32 {
	if o == nil || IsNil(o.VlanId) {
		var ret int32
		return ret
	}
	return *o.VlanId
}

// GetVlanIdOk returns a tuple with the VlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetVlanIdOk() (*int32, bool) {
	if o == nil || IsNil(o.VlanId) {
		return nil, false
	}
	return o.VlanId, true
}

// HasVlanId returns a boolean if a field has been set.
func (o *IPNetwork) HasVlanId() bool {
	if o != nil && !IsNil(o.VlanId) {
		return true
	}

	return false
}

// SetVlanId gets a reference to the given int32 and assigns it to the VlanId field.
func (o *IPNetwork) SetVlanId(v int32) {
	o.VlanId = &v
}

// GetReviewBy returns the ReviewBy field value if set, zero value otherwise.
func (o *IPNetwork) GetReviewBy() User {
	if o == nil || IsNil(o.ReviewBy) {
		var ret User
		return ret
	}
	return *o.ReviewBy
}

// GetReviewByOk returns a tuple with the ReviewBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetReviewByOk() (*User, bool) {
	if o == nil || IsNil(o.ReviewBy) {
		return nil, false
	}
	return o.ReviewBy, true
}

// HasReviewBy returns a boolean if a field has been set.
func (o *IPNetwork) HasReviewBy() bool {
	if o != nil && !IsNil(o.ReviewBy) {
		return true
	}

	return false
}

// SetReviewBy gets a reference to the given User and assigns it to the ReviewBy field.
func (o *IPNetwork) SetReviewBy(v User) {
	o.ReviewBy = &v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *IPNetwork) GetDueDate() string {
	if o == nil || IsNil(o.DueDate) {
		var ret string
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetDueDateOk() (*string, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *IPNetwork) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given string and assigns it to the DueDate field.
func (o *IPNetwork) SetDueDate(v string) {
	o.DueDate = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *IPNetwork) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *IPNetwork) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *IPNetwork) SetUrl(v string) {
	o.Url = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *IPNetwork) GetModified() time.Time {
	if o == nil || IsNil(o.Modified) {
		var ret time.Time
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *IPNetwork) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given time.Time and assigns it to the Modified field.
func (o *IPNetwork) SetModified(v time.Time) {
	o.Modified = &v
}

// GetSheets returns the Sheets field value if set, zero value otherwise.
func (o *IPNetwork) GetSheets() Sheet {
	if o == nil || IsNil(o.Sheets) {
		var ret Sheet
		return ret
	}
	return *o.Sheets
}

// GetSheetsOk returns a tuple with the Sheets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPNetwork) GetSheetsOk() (*Sheet, bool) {
	if o == nil || IsNil(o.Sheets) {
		return nil, false
	}
	return o.Sheets, true
}

// HasSheets returns a boolean if a field has been set.
func (o *IPNetwork) HasSheets() bool {
	if o != nil && !IsNil(o.Sheets) {
		return true
	}

	return false
}

// SetSheets gets a reference to the given Sheet and assigns it to the Sheets field.
func (o *IPNetwork) SetSheets(v Sheet) {
	o.Sheets = &v
}

func (o IPNetwork) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPNetwork) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["company"] = o.Company
	toSerialize["name"] = o.Name
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["site"] = o.Site
	toSerialize["networkAddress"] = o.NetworkAddress
	if !IsNil(o.DnsServer1) {
		toSerialize["dnsServer1"] = o.DnsServer1
	}
	if !IsNil(o.DnsServer2) {
		toSerialize["dnsServer2"] = o.DnsServer2
	}
	if !IsNil(o.DhcpServer) {
		toSerialize["dhcpServer"] = o.DhcpServer
	}
	if !IsNil(o.DefaultGateway) {
		toSerialize["defaultGateway"] = o.DefaultGateway
	}
	toSerialize["subnetMask"] = o.SubnetMask
	if !IsNil(o.IpVersion) {
		toSerialize["ipVersion"] = o.IpVersion
	}
	if !IsNil(o.VlanId) {
		toSerialize["vlanId"] = o.VlanId
	}
	if !IsNil(o.ReviewBy) {
		toSerialize["reviewBy"] = o.ReviewBy
	}
	if !IsNil(o.DueDate) {
		toSerialize["dueDate"] = o.DueDate
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	if !IsNil(o.Sheets) {
		toSerialize["sheets"] = o.Sheets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IPNetwork) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"company",
		"name",
		"site",
		"networkAddress",
		"subnetMask",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIPNetwork := _IPNetwork{}

	err = json.Unmarshal(data, &varIPNetwork)

	if err != nil {
		return err
	}

	*o = IPNetwork(varIPNetwork)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "company")
		delete(additionalProperties, "name")
		delete(additionalProperties, "notes")
		delete(additionalProperties, "description")
		delete(additionalProperties, "site")
		delete(additionalProperties, "networkAddress")
		delete(additionalProperties, "dnsServer1")
		delete(additionalProperties, "dnsServer2")
		delete(additionalProperties, "dhcpServer")
		delete(additionalProperties, "defaultGateway")
		delete(additionalProperties, "subnetMask")
		delete(additionalProperties, "ipVersion")
		delete(additionalProperties, "vlanId")
		delete(additionalProperties, "reviewBy")
		delete(additionalProperties, "dueDate")
		delete(additionalProperties, "url")
		delete(additionalProperties, "modified")
		delete(additionalProperties, "sheets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIPNetwork struct {
	value *IPNetwork
	isSet bool
}

func (v NullableIPNetwork) Get() *IPNetwork {
	return v.value
}

func (v *NullableIPNetwork) Set(val *IPNetwork) {
	v.value = val
	v.isSet = true
}

func (v NullableIPNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableIPNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPNetwork(val *IPNetwork) *NullableIPNetwork {
	return &NullableIPNetwork{value: val, isSet: true}
}

func (v NullableIPNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
