/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
	"fmt"
)

// checks if the KB type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KB{}

// KB struct for KB
type KB struct {
	// The unique ID of the knowledge base article.
	Id      *int64            `json:"id,omitempty"`
	Company *CompanyReference `json:"company,omitempty"`
	// The name of the knowledge base article.
	Name string `json:"name"`
	// The knowledge base article text.
	Article *string `json:"article,omitempty"`
	// A description of the knowledge base article.
	Description *string `json:"description,omitempty"`
	// A link to the knowledge base article.
	UriPath *string `json:"uriPath,omitempty"`
	// Public or not
	Public *bool `json:"public,omitempty"`
	// Knowledge base article expiration date.
	Expires     *string                `json:"expires,omitempty"`
	Category    KBCategoryReference    `json:"category"`
	SubCategory KBSubCategoryReference `json:"subCategory"`
	ReviewBy    *User                  `json:"reviewBy,omitempty"`
	// Review Due date
	DueDate *string `json:"dueDate,omitempty"`
	// The link of the knowledge base article.
	Url *string `json:"url,omitempty"`
	// in (true)/out of service (false)
	InOut *bool `json:"inOut,omitempty"`
	// Reason - why this item is being \"checked out/marked inactive\"
	InOutNotes *string `json:"inOutNotes,omitempty"`
	// The date the knowledge base article was most recently modified.
	Modified             *string `json:"modified,omitempty"`
	Sheets               *Sheet  `json:"sheets,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _KB KB

// NewKB instantiates a new KB object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKB(name string, category KBCategoryReference, subCategory KBSubCategoryReference) *KB {
	this := KB{}
	this.Name = name
	this.Category = category
	this.SubCategory = subCategory
	return &this
}

// NewKBWithDefaults instantiates a new KB object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKBWithDefaults() *KB {
	this := KB{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *KB) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *KB) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *KB) SetId(v int64) {
	o.Id = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *KB) GetCompany() CompanyReference {
	if o == nil || IsNil(o.Company) {
		var ret CompanyReference
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetCompanyOk() (*CompanyReference, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *KB) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given CompanyReference and assigns it to the Company field.
func (o *KB) SetCompany(v CompanyReference) {
	o.Company = &v
}

// GetName returns the Name field value
func (o *KB) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *KB) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *KB) SetName(v string) {
	o.Name = v
}

// GetArticle returns the Article field value if set, zero value otherwise.
func (o *KB) GetArticle() string {
	if o == nil || IsNil(o.Article) {
		var ret string
		return ret
	}
	return *o.Article
}

// GetArticleOk returns a tuple with the Article field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetArticleOk() (*string, bool) {
	if o == nil || IsNil(o.Article) {
		return nil, false
	}
	return o.Article, true
}

// HasArticle returns a boolean if a field has been set.
func (o *KB) HasArticle() bool {
	if o != nil && !IsNil(o.Article) {
		return true
	}

	return false
}

// SetArticle gets a reference to the given string and assigns it to the Article field.
func (o *KB) SetArticle(v string) {
	o.Article = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *KB) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *KB) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *KB) SetDescription(v string) {
	o.Description = &v
}

// GetUriPath returns the UriPath field value if set, zero value otherwise.
func (o *KB) GetUriPath() string {
	if o == nil || IsNil(o.UriPath) {
		var ret string
		return ret
	}
	return *o.UriPath
}

// GetUriPathOk returns a tuple with the UriPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetUriPathOk() (*string, bool) {
	if o == nil || IsNil(o.UriPath) {
		return nil, false
	}
	return o.UriPath, true
}

// HasUriPath returns a boolean if a field has been set.
func (o *KB) HasUriPath() bool {
	if o != nil && !IsNil(o.UriPath) {
		return true
	}

	return false
}

// SetUriPath gets a reference to the given string and assigns it to the UriPath field.
func (o *KB) SetUriPath(v string) {
	o.UriPath = &v
}

// GetPublic returns the Public field value if set, zero value otherwise.
func (o *KB) GetPublic() bool {
	if o == nil || IsNil(o.Public) {
		var ret bool
		return ret
	}
	return *o.Public
}

// GetPublicOk returns a tuple with the Public field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.Public) {
		return nil, false
	}
	return o.Public, true
}

// HasPublic returns a boolean if a field has been set.
func (o *KB) HasPublic() bool {
	if o != nil && !IsNil(o.Public) {
		return true
	}

	return false
}

// SetPublic gets a reference to the given bool and assigns it to the Public field.
func (o *KB) SetPublic(v bool) {
	o.Public = &v
}

// GetExpires returns the Expires field value if set, zero value otherwise.
func (o *KB) GetExpires() string {
	if o == nil || IsNil(o.Expires) {
		var ret string
		return ret
	}
	return *o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetExpiresOk() (*string, bool) {
	if o == nil || IsNil(o.Expires) {
		return nil, false
	}
	return o.Expires, true
}

// HasExpires returns a boolean if a field has been set.
func (o *KB) HasExpires() bool {
	if o != nil && !IsNil(o.Expires) {
		return true
	}

	return false
}

// SetExpires gets a reference to the given string and assigns it to the Expires field.
func (o *KB) SetExpires(v string) {
	o.Expires = &v
}

// GetCategory returns the Category field value
func (o *KB) GetCategory() KBCategoryReference {
	if o == nil {
		var ret KBCategoryReference
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *KB) GetCategoryOk() (*KBCategoryReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *KB) SetCategory(v KBCategoryReference) {
	o.Category = v
}

// GetSubCategory returns the SubCategory field value
func (o *KB) GetSubCategory() KBSubCategoryReference {
	if o == nil {
		var ret KBSubCategoryReference
		return ret
	}

	return o.SubCategory
}

// GetSubCategoryOk returns a tuple with the SubCategory field value
// and a boolean to check if the value has been set.
func (o *KB) GetSubCategoryOk() (*KBSubCategoryReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubCategory, true
}

// SetSubCategory sets field value
func (o *KB) SetSubCategory(v KBSubCategoryReference) {
	o.SubCategory = v
}

// GetReviewBy returns the ReviewBy field value if set, zero value otherwise.
func (o *KB) GetReviewBy() User {
	if o == nil || IsNil(o.ReviewBy) {
		var ret User
		return ret
	}
	return *o.ReviewBy
}

// GetReviewByOk returns a tuple with the ReviewBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetReviewByOk() (*User, bool) {
	if o == nil || IsNil(o.ReviewBy) {
		return nil, false
	}
	return o.ReviewBy, true
}

// HasReviewBy returns a boolean if a field has been set.
func (o *KB) HasReviewBy() bool {
	if o != nil && !IsNil(o.ReviewBy) {
		return true
	}

	return false
}

// SetReviewBy gets a reference to the given User and assigns it to the ReviewBy field.
func (o *KB) SetReviewBy(v User) {
	o.ReviewBy = &v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *KB) GetDueDate() string {
	if o == nil || IsNil(o.DueDate) {
		var ret string
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetDueDateOk() (*string, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *KB) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given string and assigns it to the DueDate field.
func (o *KB) SetDueDate(v string) {
	o.DueDate = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *KB) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *KB) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *KB) SetUrl(v string) {
	o.Url = &v
}

// GetInOut returns the InOut field value if set, zero value otherwise.
func (o *KB) GetInOut() bool {
	if o == nil || IsNil(o.InOut) {
		var ret bool
		return ret
	}
	return *o.InOut
}

// GetInOutOk returns a tuple with the InOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetInOutOk() (*bool, bool) {
	if o == nil || IsNil(o.InOut) {
		return nil, false
	}
	return o.InOut, true
}

// HasInOut returns a boolean if a field has been set.
func (o *KB) HasInOut() bool {
	if o != nil && !IsNil(o.InOut) {
		return true
	}

	return false
}

// SetInOut gets a reference to the given bool and assigns it to the InOut field.
func (o *KB) SetInOut(v bool) {
	o.InOut = &v
}

// GetInOutNotes returns the InOutNotes field value if set, zero value otherwise.
func (o *KB) GetInOutNotes() string {
	if o == nil || IsNil(o.InOutNotes) {
		var ret string
		return ret
	}
	return *o.InOutNotes
}

// GetInOutNotesOk returns a tuple with the InOutNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetInOutNotesOk() (*string, bool) {
	if o == nil || IsNil(o.InOutNotes) {
		return nil, false
	}
	return o.InOutNotes, true
}

// HasInOutNotes returns a boolean if a field has been set.
func (o *KB) HasInOutNotes() bool {
	if o != nil && !IsNil(o.InOutNotes) {
		return true
	}

	return false
}

// SetInOutNotes gets a reference to the given string and assigns it to the InOutNotes field.
func (o *KB) SetInOutNotes(v string) {
	o.InOutNotes = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *KB) GetModified() string {
	if o == nil || IsNil(o.Modified) {
		var ret string
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetModifiedOk() (*string, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *KB) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given string and assigns it to the Modified field.
func (o *KB) SetModified(v string) {
	o.Modified = &v
}

// GetSheets returns the Sheets field value if set, zero value otherwise.
func (o *KB) GetSheets() Sheet {
	if o == nil || IsNil(o.Sheets) {
		var ret Sheet
		return ret
	}
	return *o.Sheets
}

// GetSheetsOk returns a tuple with the Sheets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KB) GetSheetsOk() (*Sheet, bool) {
	if o == nil || IsNil(o.Sheets) {
		return nil, false
	}
	return o.Sheets, true
}

// HasSheets returns a boolean if a field has been set.
func (o *KB) HasSheets() bool {
	if o != nil && !IsNil(o.Sheets) {
		return true
	}

	return false
}

// SetSheets gets a reference to the given Sheet and assigns it to the Sheets field.
func (o *KB) SetSheets(v Sheet) {
	o.Sheets = &v
}

func (o KB) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KB) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Article) {
		toSerialize["article"] = o.Article
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.UriPath) {
		toSerialize["uriPath"] = o.UriPath
	}
	if !IsNil(o.Public) {
		toSerialize["public"] = o.Public
	}
	if !IsNil(o.Expires) {
		toSerialize["expires"] = o.Expires
	}
	toSerialize["category"] = o.Category
	toSerialize["subCategory"] = o.SubCategory
	if !IsNil(o.ReviewBy) {
		toSerialize["reviewBy"] = o.ReviewBy
	}
	if !IsNil(o.DueDate) {
		toSerialize["dueDate"] = o.DueDate
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.InOut) {
		toSerialize["inOut"] = o.InOut
	}
	if !IsNil(o.InOutNotes) {
		toSerialize["inOutNotes"] = o.InOutNotes
	}
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	if !IsNil(o.Sheets) {
		toSerialize["sheets"] = o.Sheets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KB) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"category",
		"subCategory",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKB := _KB{}

	err = json.Unmarshal(data, &varKB)

	if err != nil {
		return err
	}

	*o = KB(varKB)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "company")
		delete(additionalProperties, "name")
		delete(additionalProperties, "article")
		delete(additionalProperties, "description")
		delete(additionalProperties, "uriPath")
		delete(additionalProperties, "public")
		delete(additionalProperties, "expires")
		delete(additionalProperties, "category")
		delete(additionalProperties, "subCategory")
		delete(additionalProperties, "reviewBy")
		delete(additionalProperties, "dueDate")
		delete(additionalProperties, "url")
		delete(additionalProperties, "inOut")
		delete(additionalProperties, "inOutNotes")
		delete(additionalProperties, "modified")
		delete(additionalProperties, "sheets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKB struct {
	value *KB
	isSet bool
}

func (v NullableKB) Get() *KB {
	return v.value
}

func (v *NullableKB) Set(val *KB) {
	v.value = val
	v.isSet = true
}

func (v NullableKB) IsSet() bool {
	return v.isSet
}

func (v *NullableKB) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKB(val *KB) *NullableKB {
	return &NullableKB{value: val, isSet: true}
}

func (v NullableKB) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKB) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
