/*
Portal API 2.0

2.2.10

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package itportalapi

import (
	"encoding/json"
)

// checks if the SwitchPortRangeDataWrapper type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SwitchPortRangeDataWrapper{}

// SwitchPortRangeDataWrapper struct for SwitchPortRangeDataWrapper
type SwitchPortRangeDataWrapper struct {
	// The HTTP status code of the returned result.
	Code *int32 `json:"code,omitempty"`
	// A string description of the call status.
	Status *string                       `json:"status,omitempty"`
	Data   *SwitchPortRangeDataContainer `json:"data,omitempty"`
	// A digest value of the content returned by the call.
	Etag                 *string `json:"etag,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SwitchPortRangeDataWrapper SwitchPortRangeDataWrapper

// NewSwitchPortRangeDataWrapper instantiates a new SwitchPortRangeDataWrapper object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSwitchPortRangeDataWrapper() *SwitchPortRangeDataWrapper {
	this := SwitchPortRangeDataWrapper{}
	return &this
}

// NewSwitchPortRangeDataWrapperWithDefaults instantiates a new SwitchPortRangeDataWrapper object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSwitchPortRangeDataWrapperWithDefaults() *SwitchPortRangeDataWrapper {
	this := SwitchPortRangeDataWrapper{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *SwitchPortRangeDataWrapper) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwitchPortRangeDataWrapper) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *SwitchPortRangeDataWrapper) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *SwitchPortRangeDataWrapper) SetCode(v int32) {
	o.Code = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SwitchPortRangeDataWrapper) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwitchPortRangeDataWrapper) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SwitchPortRangeDataWrapper) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SwitchPortRangeDataWrapper) SetStatus(v string) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SwitchPortRangeDataWrapper) GetData() SwitchPortRangeDataContainer {
	if o == nil || IsNil(o.Data) {
		var ret SwitchPortRangeDataContainer
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwitchPortRangeDataWrapper) GetDataOk() (*SwitchPortRangeDataContainer, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SwitchPortRangeDataWrapper) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given SwitchPortRangeDataContainer and assigns it to the Data field.
func (o *SwitchPortRangeDataWrapper) SetData(v SwitchPortRangeDataContainer) {
	o.Data = &v
}

// GetEtag returns the Etag field value if set, zero value otherwise.
func (o *SwitchPortRangeDataWrapper) GetEtag() string {
	if o == nil || IsNil(o.Etag) {
		var ret string
		return ret
	}
	return *o.Etag
}

// GetEtagOk returns a tuple with the Etag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwitchPortRangeDataWrapper) GetEtagOk() (*string, bool) {
	if o == nil || IsNil(o.Etag) {
		return nil, false
	}
	return o.Etag, true
}

// HasEtag returns a boolean if a field has been set.
func (o *SwitchPortRangeDataWrapper) HasEtag() bool {
	if o != nil && !IsNil(o.Etag) {
		return true
	}

	return false
}

// SetEtag gets a reference to the given string and assigns it to the Etag field.
func (o *SwitchPortRangeDataWrapper) SetEtag(v string) {
	o.Etag = &v
}

func (o SwitchPortRangeDataWrapper) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SwitchPortRangeDataWrapper) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Etag) {
		toSerialize["etag"] = o.Etag
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SwitchPortRangeDataWrapper) UnmarshalJSON(data []byte) (err error) {
	varSwitchPortRangeDataWrapper := _SwitchPortRangeDataWrapper{}

	err = json.Unmarshal(data, &varSwitchPortRangeDataWrapper)

	if err != nil {
		return err
	}

	*o = SwitchPortRangeDataWrapper(varSwitchPortRangeDataWrapper)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "status")
		delete(additionalProperties, "data")
		delete(additionalProperties, "etag")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSwitchPortRangeDataWrapper struct {
	value *SwitchPortRangeDataWrapper
	isSet bool
}

func (v NullableSwitchPortRangeDataWrapper) Get() *SwitchPortRangeDataWrapper {
	return v.value
}

func (v *NullableSwitchPortRangeDataWrapper) Set(val *SwitchPortRangeDataWrapper) {
	v.value = val
	v.isSet = true
}

func (v NullableSwitchPortRangeDataWrapper) IsSet() bool {
	return v.isSet
}

func (v *NullableSwitchPortRangeDataWrapper) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSwitchPortRangeDataWrapper(val *SwitchPortRangeDataWrapper) *NullableSwitchPortRangeDataWrapper {
	return &NullableSwitchPortRangeDataWrapper{value: val, isSet: true}
}

func (v NullableSwitchPortRangeDataWrapper) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSwitchPortRangeDataWrapper) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
